### PR TITLE
solve JwtAuthenticationToken does not contains user's authorities

### PR DESCRIPTION
**Pull request by seelikes**
you can see the bug description [here](https://github.com/spring-projects/spring-security-oauth/issues/1659)

when one access restful interface guarded by spring-security-oauth2-resource-server with Jwt token, user's own authorities will be lost, so `PreAuthorize` annotation will always fail when guarding user's own authorities.

These authorities are granted to the user, regardless of what resource server it is accessing, which client it's using.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@seelikes Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6772)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6772) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@seelikes Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6772)!

**Comment by jzheaux** [comment]
@seelikes thanks for the PR!

While this is a really interesting idea, it's not clear to me that this is a common enough thing to add. `scope` and `scp` appear in [numerous](https://tools.ietf.org/html/rfc7662#section-2.2) [specifications](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-10#section-4.2) and are widely used across [many](https://developer.okta.com/docs/api/resources/oidc/#request-parameters-3) [Authorization](https://developer.okta.com/docs/api/resources/oidc/#access-token-header) [Servers](https://docs.cloudfoundry.org/api/uaa/version/4.30.0/index.html#token).

Please see https://github.com/spring-projects/spring-security/issues/6744 for some ideas on how to extract your `authorities` claim.

**Comment by seelikes** [comment]
@jzheaux if this is not fixed, PreAuthorize with Jwt can only pass client's authorities. perhaps this is not the proper way to fix it, but the problem still exist somewhere.

**Comment by GodDai** [comment]
i need this function，so sad the commit can't be merged

**Comment by jzheaux** [comment]
Note, @seelikes and @GodDai, that this can be addressed by configuring the `JwtAuthenticationConverter`, like so:

```java
protected void configure(HttpSecurity http) throws Exception { 
    http
        .authorizeRequests(authz -> authz
            // ... configure endpoints
        )
       .oauth2ResourceServer(oauth2 -> oauth2
            .jwt(jwt -> jwt
                .jwtAuthenticationConverter(jwtAuthenticationConverter())
            )
       );
}

JwtAuthenticationConverter jwtAuthenticationConverter() {
    JwtGrantedAuthoritiesConverter authorities = new JwtGrantedAuthoritiesConverter();
    authorities.setAuthoritiesClaimName("authorities");
    JwtAuthenticationConverter converter = new JwtAuthenticationConverter();
    converter.setJwtGrantedAuthoritiesConverter(authorities);
    return converter;
}
```

I've created a ticket to [add this to the reference documentation](https://github.com/spring-projects/spring-security/issues/8176). Please feel free to indicate if I've misunderstood what you are trying to achieve.

**Pull request closed without merging**
