### PR TITLE
Update expression-based.adoc

### PR DESCRIPTION
**Pull request by dmitriygrushin**
Removed a duplicate paragraph that was phrased a bit differently.

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks for the fix, @dmitriygrushin! Are you able to sign the CLA?

**Comment by jzheaux** [comment]
@dmitriygrushin, sorry, unless you sign the CLA or mark the PR as an obvious fix, I'll need to close this PR without merging. Are you able to do one or the other? If I don't hear back from you in a week or so, I'll close the PR.

**Comment by dmitriygrushin** [comment]
@pivotal-cla This is an Obvious Fix

**Comment by jzheaux** [comment]
Thanks, @dmitriygrushin, this is now merged into `6.0.x` and `main`

**Pull request merged**
