### PR TITLE
Support expressions in MethodAuthorizationDeniedHandler

### PR DESCRIPTION
**Pull request by CrazyParanoid**
Closes gh-14857

### CODE REVIEW

**Review by jzheaux — CHANGES_REQUESTED** [review]
Thanks, @CrazyParanoid! It looks like that ticket was just a little out of date. Could you please update your PR to match the syntax of the now-updated ticket?

**Comment by CrazyParanoid** [comment]
Hi @jzheaux ! Thanks for your feedback. I have updated the PR as per your comments.

**Comment by marcusdacoregio** [comment]
Thanks for the PR @CrazyParanoid. Since 6.3 is right around the corner, this feature will probably be reviewed and merged when the 6.4 branch is created. I appreciate your patience.

**Comment by marcusdacoregio** [comment]
Hi, @CrazyParanoid. Thanks for the PR, I appreciate your efforts here.

I'll close this for now for the reasons mentioned in https://github.com/spring-projects/spring-security/issues/14857#issuecomment-2229076334. Please, leave any feedback in the issue comments and let's wait for the community feedback before moving further with such feature.

**Pull request closed without merging**
