### PR TITLE
Update OAuth2IntrospectionAuthenticationToken.java

### PR DESCRIPTION
**Pull request by huytn12**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@huytn12 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6833)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6833) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@huytn12 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6833)!

**Comment by jzheaux** [comment]
@huytn12, thanks for the PR! Would you please add a test that shows that a session doesn't get created when a Resource Server is configured for opaque token? You can see a similar test for Jwt: https://github.com/spring-projects/spring-security/blob/master/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java#L544

And here is an example of a basic introspection test: https://github.com/spring-projects/spring-security/blob/master/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java#L1022

You should be able to copy the basic introspection test and change the assertion to check for a session.

**Comment by huytn12** [comment]
@jzheaux should i copy this 
`public void getWhenIntrospectingThenOk() throws Exception {
		this.spring.register(RestOperationsConfig.class, OpaqueTokenConfig.class, BasicController.class).autowire();
		mockRestOperations(json("Active"));

		this.mvc.perform(get("/authenticated")
				.with(bearerToken("token")))
				.andExpect(status().isOk())
				.andExpect(content().string("test-subject"));
                assertThat(result.getRequest().getSession(false)).isNull();
	}`

Sorry I have limited experience with Java especially creating a test

**Comment by jzheaux** [comment]
@huytn12 yes, something like that would work. Make sure to give the test its own name that follows the convention.

**Comment by jzheaux** [comment]
@huytn12 are you able to add the test? Is there something I can do to help?

**Comment by jzheaux** [comment]
Closing in favor of https://github.com/spring-projects/spring-security/pull/6841

**Pull request closed without merging**
