### PR TITLE
LDAP PasswordComparisonAuthenticator now supports salted-SHA passwords.

### PR DESCRIPTION
**Pull request by visusnet**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@visusnet Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@visusnet Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by visusnet** [comment]
The CLA has been signed.

**Comment by pivotal-issuemaster** [comment]
@visusnet Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=63)!

**Comment by rwinch** [comment]
Thanks for the PR @visusnet! Closing since the PasswordEncoder in core has been removed in favor of the crypto PasswordEncoder which handles the salt for users. If we can get an update using the existing APIs, we can consider merging this.

**Pull request closed without merging**
