### PR TITLE
Add denyAll method in AuthorizePayloadsSpec.Access

### PR DESCRIPTION
**Pull request by jascama**
See gh-7437

Co-authored-by: Eddú Meléndez <eddu.melendez@gmail.com>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jascama Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=7451)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=7451) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by jascama** [comment]
Hi, I already signed the CLA but looks like it haven't been processed.

**Comment by pivotal-issuemaster** [comment]
@jascama Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=7451)!

**Comment by eddumelendez** [comment]
@rwinch do you think this PR makes sense and can be merged anytime soon?

**Pull request merged**
