### PR TITLE
Support new event for indicates logout success

### PR DESCRIPTION
**Pull request by kazuki43zoo**
- [x] I have signed the CLA

Fixes gh-3307

Original PR is gh-222.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kazuki43zoo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@kazuki43zoo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kazuki43zoo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=3883)!

**Comment by rwinch** [comment]
@kazuki43zoo Thanks for the PR!

I think it might make more sense to place this in a `LogoutHandler` so that the logic can be reused wherever a logout occurs. Specifically, I think it makes sense in the `SecurityContextLogoutHandler`

**Comment by kazuki43zoo** [comment]
@rwinch Thanks for comment!!  I will remake this and submit a other PR at later.

**Pull request closed without merging**
