### PR TITLE
SEC-1947: Make DefaultRedirectStrategy more extensible 

### PR DESCRIPTION
**Pull request by deki**
The DefaultRedirectStrategy should be extensible to allow custom implementations (e.g. for AJAX handling or special relative URLs).
JIRAs: SEC-1947, SEC-1765

I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@deki Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by deki** [comment]
I've already signed it, seems it was enough to authorize the new CLA tool to migrate it.

**Comment by pivotal-issuemaster** [comment]
@deki Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@deki Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by jgrandja** [comment]
Thanks for submitting this PR @deki.
The only change I made is to provide a protected accessor for the `contextRelative` member instead of making it protected.
This is now merged to master.
Thanks!

**Pull request closed without merging**
