### PR TITLE
Provide Jackson serialization support for LDAP classes

### PR DESCRIPTION
**Pull request by markusheiden**

### CODE REVIEW

**Comment by pengliaoye** [comment]
which time to merge this pull request

**Review by eleftherias — CHANGES_REQUESTED** [review]
Thanks for the PR @markusheiden!
Please include some tests for these changes. You can see similar tests in [OAuth2AuthorizedClientMixinTests](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/jackson2/OAuth2AuthorizedClientMixinTests.java).

**Comment by pengliaoye** [comment]
any progress?

**Comment by markusheiden** [comment]
I'm a bit low on time currently, but I will provide the tests.

**Comment by eleftherias** [comment]
Hey @markusheiden, would you like to continue working on this PR or would you prefer if someone from the team picked up from where you left off?

**Comment by markusheiden** [comment]
Yes. Sorry for not being able to provide the tests in a timely manner...

Status quo: The tests I added are mostly empty shells or copy and paste from existing tests.

**Pull request closed without merging**
