### PR TITLE
Fix no check if the parameter is null.

### PR DESCRIPTION
**Pull request by JokerSun**
> https://github.com/spring-projects/spring-security/issues/6773#issue-432523187

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@JokerSun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6775)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6775) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@JokerSun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6775)!

**Comment by JokerSun** [comment]
@jzheaux Thanks for your review, i guess your are right , and can you make some suggestion about strategy of 'null value' it's import for my developing, because i don't know when should i catch the null value or throw exception.

**Comment by jzheaux** [comment]
Thanks, @JokerSun for the update!

To answer your question about checking for null, remember that the more possible inputs you allow, the more you have to support. Ask yourself if it would be a normal use case to pass a null value to your method - if not, throw an `IllegalArgumentException`. 

Regarding your PR, will you please do some cleanup before it gets merged? It looks like there are five commits, but only one line changed. Can you make so that there is only one commit? And then please format the commit this way:

```
AuthorityUtils Null Check

Fixes: gh-6773
```

Thanks!

**Comment by JokerSun** [comment]
@juzerali I am sorry about reply later, i have clean the commits, and thanks for your suggestion very much.

**Comment by jzheaux** [comment]
Thanks, again, @JokerSun! This has been merged into `master`.

**Pull request merged**
