### PR TITLE
OAuth2LoginAuthenticationFilter sets AuthenticationDetails

### PR DESCRIPTION
**Pull request by ddevrien**
[GH-6866] OAuth2LoginAuthenticationFilter should set AuthenticationDetails

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ddevrien Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6884)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6884) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ddevrien Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6884)!

**Comment by ddevrien** [comment]
@rwinch let me know if I need to change anything else :)

**Comment by rwinch** [comment]
Thanks for the PR @ddevrien! This is now fixed in master

**Pull request merged**
