### PR TITLE
Update to nimbus-jose-jwt:6.7

### PR DESCRIPTION
**Pull request by darthCodr**
Update version of nimbus-jose-jwt from 6.5.1 to 6.7.

Fixes: gh-6459

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@darthCodr Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6464)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6464) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@darthCodr Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6464)!

**Comment by jzheaux** [comment]
@darthCodr, thanks for the PR! It looks like this has commits from one of your previous PRs. Would you please rebase your branch with `master` and force-push your commit again?

If I had configured the Spring Security upstream to be `spring-projects` and my own fork as `origin`, then I'd do something like this:

```bash
git fetch spring-projects
git checkout gh-6459
git rebase spring-projects/master
git push origin +gh-6459
```

To check the name of each remote, you can do `git remote -v`, and it will be in the first column on the left.

**Comment by darthCodr** [comment]
Hi @jzheaux. Thanks for your response. I have followed the steps and made the fixes. Kindly confirm the PR is fine.

**Comment by jzheaux** [comment]
Looks good! Thanks for the PR, @darthCodr, this is now merged into `master`.

**Pull request merged**
