### PR TITLE
Documented dependencies for opaque Resource Server

### PR DESCRIPTION
**Pull request by pgerhard**
As discussed in #8391, extended the documentation for the opaque Resource Server in order to clearly state which dependencies are required in order for the minimal deployment to work.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR @pgerhard! Could you please update the commit to match our Contributor guidelines. In particular it should end with an empty new line and then `Closes gh-8391`

**Comment by pgerhard** [comment]
@rwinch oops. Sorry I will get right on that. While doing this I just noticed that the link to the Contributor guidelines in the README.md is dead. Can I fix this in the PR or do we need an extra ticket?

**Comment by rwinch** [comment]
@pgerhard Ahh good catch. Please send a separate PR for that.

**Comment by rwinch** [comment]
I just went ahead and merged. Thanks again for the PR!

**Pull request merged**
