### PR TITLE
SEC-3157 deleteEntries in updateAcl causing deadlocks with concurrent updates

### PR DESCRIPTION
**Pull request by truevektordev**
SEC-3157: change to JdbcMutableAclService.updateAcl to prevent deadlocks

Added a count check to the acl_entry table for the OID so updateAcl only deletes if there are rows to delete.

NOTE: I still need to write a test to reproduce this.

### CODE REVIEW

**Comment by truevektordev** [comment]
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

**Comment by rwinch** [comment]
Thanks for the PR! I will wait until you get a test to reproduce this.

**Comment by awakenalive** [comment]
Sorry I haven't gotten the test written for this yet. The holiday and work after it have gotten in the way...

Worst case scenario, I'll probably get the tests during the week of Christmas...

**Comment by rwinch** [comment]
@awakenalive Thanks for the follow up! No problem if you can't get to it until the week of Christmas. It will be a great Christmas present :)

**Comment by pivotal-issuemaster** [comment]
@truevektordev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@truevektordev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by rwinch** [comment]
Pushing back till tests are submitted

**Comment by eleftherias** [comment]
@truevektordev Have you had the chance to look into adding a test for this?

**Comment by eleftherias** [comment]
@awakenalive Are you working on this and have you had the chance to look into adding a test for it?

**Pull request closed without merging**
