### PR TITLE
Fix documentation typos

### PR DESCRIPTION
**Pull request by izeye**
This PR simply fixes typos.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@izeye Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=3944)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by izeye** [comment]
`Click here` links to https://github.com/spring-projects/spring-security/pull/null which is 404.

**Comment by pivotal-issuemaster** [comment]
@izeye Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=3944)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@izeye Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=3944)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=3944) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@izeye Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=3944)!

**Comment by rwinch** [comment]
@izeye Thanks for the pull request for report on our CLA tooling!

We are still working out some of the bugs. [The issue](https://github.com/pivotalsoftware/pivotal-cla/pull/114) is now fixed and I have synched the status.

Thanks again!

**Comment by rwinch** [comment]
Thanks for the PR! This is merged via 310bb39a0dc7e719167a9006f5f8505affdaad94

**Pull request closed without merging**
