### PR TITLE
Fix Assert usage

### PR DESCRIPTION
**Pull request by Shredder121**
This changes the `Assert.notNull()` to not operate on the message, which is never null.

- [x] I have signed the CLA, previously on Spring Boot, with [knowledge of it on the spring-framework repo](https://github.com/spring-projects/spring-framework/pull/986#issuecomment-192209403).

```
Thank you but our records indicate that you have already accepted the individual contributor agreement.
If you are interested in participating in an additional Spring project, please contact the appropriate project lead and indicate that you have already signed the Spring Contributor Agreement.
Once signed agreement covers participating in as many Spring projects as you need.
```

### CODE REVIEW

**Comment by rwinch** [comment]
@Shredder121 Thanks for the PR! Any chance I could persuade you to include a test?

**Comment by Shredder121** [comment]
Well, I guess so, but what kind of test would that be?
Just assert that the setter in fact throws on null input?

Also, we can remove the nullcheck inside the class on `rememberMeServices` now, do you want me to do that?

**Comment by rwinch** [comment]
> Just assert that the setter in fact throws on null input?

Right. Something like `@Test(expected = IllegalArgumentException.class)`

> Also, we can remove the nullcheck inside the class on rememberMeServices now, do you want me to do that?

Yes please.

**Comment by Shredder121** [comment]
There, I pushed the test first to show the failure.

**Comment by Shredder121** [comment]
Hm.. pushed them too fast, one second.

**Comment by pivotal-issuemaster** [comment]
@Shredder121 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by Shredder121** [comment]
But the checkbox is right there!
I already signed it.

**Comment by Shredder121** [comment]
>We noticed you or a company on your behalf previously signed an agreement and imported it into our new tooling!

@pivotal-issuemaster  Happy now, bot?

**Comment by Shredder121** [comment]
Just wondering, is the source code for the bot somewhere?

**Comment by Shredder121** [comment]
Redid it, for some reason it now said "Thank you for signing the Agreement!".

**Comment by Shredder121** [comment]
Just did the process again. It didn't look like it actually was signed (Why would it give that message?)

**Comment by Shredder121** [comment]
I'm closing and reopening this PR.

```
The Pull Request Status Did Not Update
If the status of a Pull Request did not update:

If the GitHub status did not update, check https://status.github.com. If GitHub is having issues, the event may have not been sent to the application.
If your went directly to the tooling vs using the link provided on the Pull Request, the Pull Request will not be automatically updated. You can update the status bYou can re-trigger a notification by closing and reopening the Pull Request.
You can force an update of the status bYou can re-trigger a notification by closing and reopening the Pull Request.
```

**Comment by rwinch** [comment]
@Shredder121 Sorry for the trouble. The security related projects are trying out the new CLA tooling and it appears we have a few bugs to sort out.

It looks like the GitHub hook has failed to register for some reason. I will look into this. See https://github.com/pivotalsoftware/pivotal-cla/issues/103

**Comment by Shredder121** [comment]
@rwinch Oh that's fine, I already figured there were some issues.
Nice to see that it's open source though!

**Comment by pivotal-issuemaster** [comment]
@Shredder121 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

**Comment by pivotal-issuemaster** [comment]
@Shredder121 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by rwinch** [comment]
Thanks for the PR! This is now merged into master via ca76e8d784b27cb2bcd4e9080be09545b4479b52

**Comment by Shredder121** [comment]
@rwinch Hello.
There are two more commits that have to be applied: the test, and the fix for the bug.
The last commit is merely a cleanup (since after the fix, the field is never set to null).

**Comment by Shredder121** [comment]
[Resolved now, thanks](https://github.com/spring-projects/spring-security/commit/ca76e8d784b27cb2bcd4e9080be09545b4479b52#commitcomment-17934809).

**Pull request closed without merging**
