### PR TITLE
Add setContentLengthLong detection to OnCommittedResponseWrapper.

### PR DESCRIPTION
**Pull request by danielwegener**
Fixes gh-#7261

Trivial implementation.

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks, @danielwegener, for the PR! In preparation for merging, would you please update your commit message to follow [the contribution guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#format-commit-messages)?

**Comment by danielwegener** [comment]
@jzheaux Good point, sorry, wasn't reading the guildelines carefully enough. SLA is signed.

**Comment by jzheaux** [comment]
Thanks, @danielwegener! This is now merged into `master`.

**Comment by danielwegener** [comment]
Thanks @jzheaux, that's great! Is there any chance this could find a way down into 5.1.7?

**Comment by jzheaux** [comment]
Yes, @danielwegener, I've just backported it via https://github.com/spring-projects/spring-security/commit/f28fe2d5017a8f06f28877f7450320a17bb72bb6

**Pull request merged**
