### PR TITLE
Allow configure cusomized Authentication Filter

### PR DESCRIPTION
**Pull request by quaff**
After this commit, user can replace built-in AuthenticationFilter with their own. for example, obtain username and password from request body instead of parameters.
```java
http.formLogin().authenticationFilter(new RestfulUsernamePasswordAuthenticationFilter(authenticationManager(), objectMapper))
```
```java
public class RestfulUsernamePasswordAuthenticationFilter extends UsernamePasswordAuthenticationFilter {

	private static final String ATTR_NAME_REQUEST_BODY = "_REQUEST_BODY";

	private final ObjectMapper objectMapper;

	public RestfulUsernamePasswordAuthenticationFilter(AuthenticationManager authenticationManager,
			ObjectMapper objectMapper) {
		super(authenticationManager);
		this.objectMapper = objectMapper;
	}

	@Nullable
	protected String obtainUsername(HttpServletRequest request) {
		Map<String, String> requestBody = body(request);
		if (requestBody != null) {
			request.setAttribute(ATTR_NAME_REQUEST_BODY, requestBody);
			return requestBody.get(getUsernameParameter());
		}
		return super.obtainUsername(request);
	}

	@Nullable
	protected String obtainPassword(HttpServletRequest request) {
		@SuppressWarnings("unchecked")
		Map<String, String> requestBody = (Map<String, String>) request.getAttribute(ATTR_NAME_REQUEST_BODY);
		if (requestBody != null) {
			request.removeAttribute(ATTR_NAME_REQUEST_BODY);
			return requestBody.get(getPasswordParameter());
		}
		return super.obtainPassword(request);
	}

	@Nullable
	private Map<String, String> body(HttpServletRequest request) {
		String contentType = request.getContentType();
		if (contentType != null) {
			if (MediaType.parseMediaType(contentType).isCompatibleWith(APPLICATION_JSON)) {
				try {
					return objectMapper.readValue(request.getInputStream(), new TypeReference<Map<String, String>>() {
					});
				} catch (Exception e) {
					log.error(e.getMessage(), e);
				}
			}
		}
		return null;
	}
}
```

### CODE REVIEW

**Comment by jzheaux** [comment]
Thank you for putting this PR together, @quaff. What you are proposing is already possible like so:

```java
http
    .addFilter(new RestfulUsernamePasswordAuthenticationFilter(...));
```

As such, I'm going to close this PR. Please feel free to open a ticket if you feel like something is missing from `addFilter`.

**Comment by quaff** [comment]
> Thank you for putting this PR together, @quaff. What you are proposing is already possible like so:
> 
> ```java
> http
>     .addFilter(new RestfulUsernamePasswordAuthenticationFilter(...));
> ```
> 
> As such, I'm going to close this PR. Please feel free to open a ticket if you feel like something is missing from `addFilter`.

No, I want extend and replace the default implementation not add new one, someone else want this too:
https://stackoverflow.com/questions/23817524/how-to-replace-usernamepasswordauthenticationfilter-in-spring-security

**Comment by quaff** [comment]
> Thank you for putting this PR together, @quaff. What you are proposing is already possible like so:
> 
> ```java
> http
>     .addFilter(new RestfulUsernamePasswordAuthenticationFilter(...));
> ```
> 
> As such, I'm going to close this PR. Please feel free to open a ticket if you feel like something is missing from `addFilter`.

`addFilter` cannot replace existing one, and is not type safe like this PR.

**Comment by arthursalimkhanov** [comment]
> Thank you for putting this PR together, @quaff. What you are proposing is already possible like so:
> 
> ```java
> http
>     .addFilter(new RestfulUsernamePasswordAuthenticationFilter(...));
> ```
> 
> As such, I'm going to close this PR. Please feel free to open a ticket if you feel like something is missing from `addFilter`.

This is not at all what you wrote about and yes it is really necessary

**Comment by arthursalimkhanov** [comment]
@quaff [ISSUE](https://github.com/spring-projects/spring-security/issues/10116)

**Comment by jzheaux** [comment]
Does `addFilterAt` achieve what you are wanting to do? For example

```java
http.addFilterAt(new RestfulUsernamePasswordAuthenticationFilter(...), UsernamePasswordAuthenticationFilter.class)
```

**Comment by jzheaux** [comment]
To reduce some of the noise between the related tickets, I'm going to reassign this to @eleftherias. It appears that you and she first started chatting about this on #10119.

**Comment by quaff** [comment]
> Does `addFilterAt` achieve what you are wanting to do? For example
> 
> ```java
> http.addFilterAt(new RestfulUsernamePasswordAuthenticationFilter(...), UsernamePasswordAuthenticationFilter.class)
> ```
No, it's adding new filter not replacing existing.

**Pull request closed without merging**
