### PR TITLE
Content Negotiating Logout Success Handler #3282

### PR DESCRIPTION
**Pull request by shazin**

### CODE REVIEW

**Comment by rwinch** [comment]
@shazin Thanks for the PR!

I think I'd prefer to make something a little more flexible. Perhaps a RequestMatcherLogoutHandler would make more sense. The implementation would have a `LinkedHashMap` of `RequestMatcher` to `LogoutHandler` that is injected into it. The first `RequestMatcher` that is matched on would have its corresponding `LogoutHandler` invoked. There would also be a default `LogoutHandler` if no `RequestMatcher` were matched

**Comment by shazin** [comment]
The requested changes are pushed.

**Comment by rwinch** [comment]
@shazin Thanks for the fast response! A few more things:

* We should include some documentation updates
* Why the constructor? I think it is unlikely to be correct since users will probably want to customize the logout success URL.
* I think it is best to have a default `LogoutSuccessHandler` so that users know that something was executed.
* Sorry. I think I misguided you on the name of the class. To be consistent with the current architecture (i.e. `DelegatingAccessDeniedHandler`, `DelegatingAuthenticationEntryPoint`, etc) we should use the name `DelegatingLogoutSuccessHandler`

**Comment by rwinch** [comment]
Thank you for the PR! I have included these changes along with the necessary polish in gh-3828

Closing in favor of gh-3828

**Pull request closed without merging**
