### PR TITLE
Fix broken link in spring security reference document

### PR DESCRIPTION
**Pull request by dkodippily**
Fixes: #8593

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dkodippily Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8618)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=8618) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dkodippily Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8618)!

**Comment by jzheaux** [comment]
@dkodippily thanks for the PR, and congrats on your first open-source contribution!

Would you please change the commit message to say "Fixes" instead of "Issue"? When it says "Fixes" we (and GitHub) know that there's nothing left to do on the related ticket so it can be closed.

**Comment by dkodippily** [comment]
@jzheaux Done.

**Comment by jzheaux** [comment]
Great, @dkodippily! This is now merged into `master`. Thank you again for your initiative, and I'd encourage you to look for [more places to contribute](https://github.com/spring-projects/spring-security/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+ideal-for-contribution%22).

**Comment by dkodippily** [comment]
@jzheaux Thanks for all the support.

**Pull request merged**
