### PR TITLE
Allow logout+jwt JWT type

### PR DESCRIPTION
**Pull request by OLibutzki**
Backport of the solution for #15003 to `6.2.x` .

### CODE REVIEW

**Comment by jzheaux** [comment]
Hi, @OLibutzki. It looks like the build is failing. Are you able to repair it? It looks like the commit you backported is using a method that doesn't exist in `6.2.x`.

**Comment by OLibutzki** [comment]
Hi @jzheaux,

obviously, I have been too optimistic by cherry-picking the commit. I fixed the error. 

`OidcIdTokenDecoderFactory.createDefaultClaimTypeConverter()` has been introduced in 6.3, so when merging to `6.3.x` this new method should be used.

**Comment by OLibutzki** [comment]
@jzheaux anything I can do to push this issue ahead? For our application it's curcial to use Keycloak 25 and therefore it would help us a lot to ensure Spring Security's compatibility.

**Comment by jzheaux** [comment]
Thanks, @OLibutzki, this is now merged into `6.2.x` and forward ported to `6.3.x`

**Pull request merged**
