### PR TITLE
AclClassIdUtils should be public

### LINKED ISSUE #4814: AclClassIdUtils should be public
### Summary

In #4424 I added `AclClassIdUtils` to handle some common logic for dealing with acl classes with types other than Long. I thought this class would be internal, then decided it was better to have it explicitly defined.

The class has package level visibility, but should be public.

### Actual Behavior

Unable to define a bean of type AclClassIdUtils using Java Config as the class is not public.

### Expected Behavior

Should be able to define a bean of type AclClassIdUtils using Java Config.

### Configuration

`@Bean
public AclClassIdUtils aclClassIdUtils() {

    AclClassIdUtils classIdUtils = new AclClassIdUtils();
    classIdUtils.setConversionService(new DefaultConversionService());
    
    return classIdUtils
}
`

### PR DESCRIPTION
**Pull request by pwheel**
AclClassIdUtils was added in #4424 but should be made public so can be instantiated via Java Config.

Fixes #4814

### CODE REVIEW

**Comment by pwheel** [comment]
Hi @rwinch can you take a look at this please? Minor fix to enable Java Config to be used.

Thanks,
Paul

**Comment by rwinch** [comment]
Thanks for the PR and the ping.

I think perhaps a better way of handling this is to allow injecting the `ConversionService` into classes using `AclClassIdUtils` and then internally the setter method creates a `AclClassIdUtils` instance with the `ConversionService`.

**Comment by pwheel** [comment]
Yep, that sounds good @rwinch, thanks. I was never quite happy with this bit, I like your suggestion.

I've made the changes.
Cheers.

**Comment by pwheel** [comment]
@rwinch ping :-)

**Comment by pwheel** [comment]
Hi @rwinch are you able to give some feedback on this? I've made some changes in keeping with your suggestions I hope.

Thanks,
Paul

**Comment by rwinch** [comment]
Thanks for the PR & sorry for the delays @pwheel! This is now merged into master

**Comment by pwheel** [comment]
No worries @rwinch I should have chased you harder! 😄 That's awesome, thanks a lot

**Comment by rwinch** [comment]
It was all me. I need to be better about being responsive (I'm focusing on that going forward) Thanks again for the PR!

**Pull request merged**
