### PR TITLE
dark-mode problem due to transparency has been fixed

### PR DESCRIPTION
**Pull request by best-rion**
In spring-security documentation page I was having difficulty to read diagrams in dark mode. Because their backgrounds were transparent and text black. So  I converted the background of all diagrams to white and fixed the problem.

It provides a better user experience.

ImageMagick was used for conversion. The command used in the process :

~/spring-security/docs/modules/ROOT/assets/images/servlet$
mogrify -background white -alpha remove -alpha off `find . -name '*.png'`

Correct Image Rendering in Dark Mode

Closes gh-14834

### CODE REVIEW

**Comment by jzheaux** [comment]
Hi, @best-rion! I appreciate all your work here. Instead of changing the image transparency, though, will you please take a look at [this ticket](https://github.com/spring-projects/spring-security/issues/14834) and [this feature](https://github.com/spring-io/antora-ui-spring/commit/ff212836b4a9ce5227ad453cde9b7cd51918968c#diff-ef5487e6a11a32cbdae799be763ba8942277b34284d796ec07d7203983d1a442R148)?

Essentially, I think you can do the following to each image reference:

```diff
+ [.invert-dark]
image::<image-name>
```

And then all the images can remain transparent.

**Comment by jzheaux** [comment]
Also, would you please include the following ticket at the end of your comment:

```
Correct Image Rendering in Dark Mode

Closes gh-14834
```

This integrates with our ticket workflow a little better. It also allows folks to research more deeply when they want to know why a given change was made.

**Comment by best-rion** [comment]
> Hi, @best-rion! I appreciate all your work here. Instead of changing the image transparency, though, will you please take a look at [this ticket](https://github.com/spring-projects/spring-security/issues/14834) and [this feature](https://github.com/spring-io/antora-ui-spring/commit/ff212836b4a9ce5227ad453cde9b7cd51918968c#diff-ef5487e6a11a32cbdae799be763ba8942277b34284d796ec07d7203983d1a442R148)?
> 
> Essentially, I think you can do the following to each image reference:
> 
> ```diff
> + [.invert-dark]
> image::<image-name>
> ```
> 
> And then all the images can remain transparent.

Do you mean changing background-color through css instead of using images with white background?

**Comment by jzheaux** [comment]
Yes. `spring-ui-antora`'s CSS has a class, `invert-dark`, that we can use.

**Comment by best-rion** [comment]
Yeah, go ahead. I have been busy since then. Do whatever you can, just fix the readability problem. I will appreciate that.

**Pull request closed without merging**
