### PR TITLE
Fixed Git SCM book link

### PR DESCRIPTION
**Pull request by mibo**
Obvious Fix (for CLA Tooling)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mibo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6203)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6203) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by rwinch** [comment]
Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@mibo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6203)!

**Comment by rwinch** [comment]
Thanks for the PR @mibo! I merged this into master

**Pull request merged**
