### PR TITLE
Fix links in oauth2 doc

### PR DESCRIPTION
**Pull request by wassan128**
I found and fixed some broken links related `ClientRegistration` in "oauth2-login.adoc".

Closes https://github.com/spring-projects/spring-security/issues/8213

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wassan128 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8214)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=8214) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wassan128 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8214)!

**Comment by rwinch** [comment]
Thanks for the Pull Request! This is now merged into master :smile:

**Comment by jgrandja** [comment]
@wassan128 @rwinch I just reviewed these updates and all 4 updated links are broken. There was no issue with the original links. This should be reverted.

**Comment by wassan128** [comment]
@jaffadog @rwinch I couldn't reach contents about "ClientRegistration" because there are in another file(oauth2-client.adoc, not oauth2-login.adoc), so I was going to fix.
Sorry if it was not what you intended.

**Comment by jgrandja** [comment]
@wassan128 If you were using an **asciidoc viewer** then yes it's possible that you were not able to access the `ClientRegistration` section from `oauth2-logic.adoc`, since that section is in another file `oauth2-client.adoc` - it depends on the capability of the asciidoc viewer though. Either way, this really should be validated by viewing the **generated html output** using the command `./gradlew docs`, which will generate the full html output. You will see that the **named anchor links** are valid and do link to the `ClientRegistration` section.

**Comment by wassan128** [comment]
@jgrandja I see. I was reading documents with GitHub web UI, so it was happen.
Thank you for helping me understand with your explanation.

**Pull request merged**
