### PR TITLE
Issue #6731 improve performance of checking headers

### PR DESCRIPTION
**Pull request by LukeButters**
#6731 Improves the performance of checking headers for new lines.

### CODE REVIEW

**Comment by jzheaux** [comment]
@LukeButters thanks, this looks great. 

Will you do just one update for me, and that is to amend your commit message so that it has "Fixes: gh-6731" at the bottom? This will make so that the associated issue automatically closes.

**Comment by LukeButters** [comment]
Hi, I used `git commit --amend` to add "Fixes: gh-6731" and it looks like it worked let me know if I need to do anything else.

**Comment by jzheaux** [comment]
Thanks for the PR, @LukeButters! This is now in `master`.

**Comment by LukeButters** [comment]
oh fantastic, thank you.

**Pull request merged**
