### PR TITLE
Fixed document error

### PR DESCRIPTION
**Pull request by henryL1N**
Issue: #5442

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@henryL1N Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=5443)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=5443) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@henryL1N Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=5443)!

**Comment by jzheaux** [comment]
Thanks @henryL1N! In the future, if you use the phrase "Fixes" instead of "Issue", merging the PR will also close the issue automatically.

**Comment by henryL1N** [comment]
Got it. Thanks for your advice.

**Pull request merged**
