### PR TITLE
SEC-1869 additions: SuccessHandler and FailureHandler for pre-auth filter implementation

### PR DESCRIPTION
**Pull request by sryll**
This is a solution I want to suggest to address the issue described in https://jira.springsource.org/browse/SEC-1869

The point is that the documentation states that AuthenticationSuccessHandlers and AuthenticationFailureHandlers can be used to react to (un)successful authentication events. As these handlers receive request and response objects via their signature, they are more powerful than reacting to AuthenticationEvents.

<quote from documentation, PDF section 9.4>
The destination following a successful authentication or an authentication failure is controlled by the AuthenticationSuccessHandler and  AuthenticationFailureHandler strategy interfaces, respectively.
</quote>

This pull request adds support for both handlers types to pre-authenticated filter implementations by amending AbstractPreAuthenticatedProcessingFilter.

If that patch needs some more work to be ready for inclusion, pls let me know.

I have submitted the CLA in 2011 already, in the context of SEC-1793.

### CODE REVIEW

**Comment by sryll** [comment]
Just checking back after a while, and wondering what the "Waiting for triage" label means for me? Is there any expectation attached and I missed something?

**Comment by rwinch** [comment]
@sryll Thanks for the bump. Waiting for triage means that we haven't gotten a good understanding of the issue yet.

I took a look at the issue and I'm not certain I understand the reasoning for wanting the AuthenticationSuccessHandler and AuthenticationFailureHandler in a pre authenticated scenario. Can you describe to me what you are doing in those scenarios?

The reason I am asking is because typically a AuthenticationSuccessHandler and AuthenticationFailureHandler will commit the response. This makes sense for form based login where we must then trigger the original request (authentication success) or send to a page that a user can re-enter credentials (authentication failure). However, a PreAuthenticationFilter will continue invoking the FilterChain which will likely cause failures.

**Comment by sryll** [comment]
@rwinch The use case I have is to have a hook to initialize the HttpSession after a successful authentication. I want to load some user data, preferences etc. from a database upon login and then store it in the session.
I don't have a similar story for the fail-handler, but it looked sensible to do it consistently.

Is there maybe some better way to achieve this session init?

**Comment by pivotal-issuemaster** [comment]
@sryll Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@sryll Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sryll Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=69)!

**Comment by sryll** [comment]
Equivalent changes have been merged in the meantime with the fix for issue #3389

**Pull request closed without merging**
