### PR TITLE
Add readme md

### PR DESCRIPTION
**Pull request by shaehnel**
this pull request is about adding a README.md and removing the current readme.txt. I have adjusted the broken links and aligned the build instructions.

I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! A markdown based README is certainly a steup up from the txt based one.

We generally use [aciidoctor](http://asciidoctor.org/docs/asciidoc-writers-guide/). Can you convert this to README.adoc using asciidoctor?

* [quick reference](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/)
* [md to adoc guide](https://github.com/graphitefriction/oscon-2013-docs-workshop/blob/master/convert-markdown-to-asciidoc.adoc)

**Comment by shaehnel** [comment]
I converted the file to asciidoctor using Spring Boot's README.adoc as a reference. I had to adjust the links and text a bit so please let me know if this is not yet the way it should be.

**Comment by rwinch** [comment]
Thanks for the updated PR! I created [SEC-2871](https://jira.spring.io/browse/SEC-2871) to track this change. I [squashed your commits](https://github.com/spring-projects/spring-security/commit/f0be6e5a619dfa6863b536d32fb9a30ce37ac180) and applied a [little polish](https://github.com/spring-projects/spring-security/commit/440fc0aba174367eb2bb1e330c2ce172743182c2) and merged this into master and 3.2.x. Thanks again!

**Comment by shaehnel** [comment]
Thank you! I just realized that the last line of README.adoc says Spring Boot where it should say Spring Security.

**Comment by rwinch** [comment]
@shaehnel Thanks this is fixed

**Pull request closed without merging**
