### PR TITLE
SEC-2548: Publish SwitchUser events after SecurityContextHolder changed

### PR DESCRIPTION
**Pull request by jmcshane**
SEC-2548: Publish SwitchUser events after SecurityContextHolder changed

[Associated JIRA](https://jira.spring.io/browse/SEC-2548)

As described in SEC-2548, currently the AuthenticationSwitchUserEvent 
is published before the authentication is set in the SecurityContextHolder. 
This commit changes the ordering of these two things, the Authentication
 object is set in the SecurityContextHolder and then the corresponding
 event is published.  The event publishing was moved from the 
requiresSwitchUser and requiresExitUser into the doFilter method.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR. Unfortunately this does not compile (in the current master or in your branch). When trying to build using:

  ./gradlew build

I get the following compile errors

```
warning: [options] bootstrap class path not set in conjunction with -source 1.5
spring-security/web/src/main/java/org/springframework/security/web/authentication/switchuser/SwitchUserFilter.java:162: error: constructor AuthenticationSwitchUserEvent in class AuthenticationSwitchUserEvent cannot be applied to given types;
                    eventPublisher.publishEvent(new AuthenticationSwitchUserEvent(
                                                ^
  required: Authentication,UserDetails
  found: Authentication,Authentication
  reason: actual argument Authentication cannot be converted to UserDetails by method invocation conversion
spring-security/web/src/main/java/org/springframework/security/web/authentication/switchuser/SwitchUserFilter.java:183: error: cannot find symbol
                eventPublisher.publishEvent(new AuthenticationSwitchUserEvent(current, originalUser));
                                                                              ^
  symbol:   variable current
  location: class SwitchUserFilter
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: spring-security/web/src/main/java/org/springframework/security/web/savedrequest/SavedRequestAwareWrapper.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
1 warning
:spring-security-web:compileJava FAILED 
```

**Comment by pivotal-issuemaster** [comment]
@jmcshane Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@jmcshane Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by rwinch** [comment]
Closing due to lack of feedback

**Pull request closed without merging**
