### PR TITLE
Fix beanResolver missing in CurrentSecurityContextArgumentResolver.

### PR DESCRIPTION
**Pull request by happier233**
CurrentSecurityContextArgumentResolver has **'beanResolver'** property, but never used. I think it might be missed.
I test the AuthenticationPrincipal annotation and CurrentSecurityContext annotation, CurrentSecurityContext annotation expression cannot work with bean.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@happier233 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9331)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=9331) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@happier233 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9331)!

**Review by jzheaux — CHANGES_REQUESTED** [review]
Nice catch, @happier233! Would you please add a test that demonstrates that `beanResolver` is now getting used?

**Comment by jzheaux** [comment]
@happier233 are you able to make the requested changes to your PR?

**Comment by happier233** [comment]
@jzheaux  I'm very sorry for costing many days to add the test to the PR, but I don't know where the code in my PR caused the format error.

**Comment by jzheaux** [comment]
No problem, @happier233. I've merged your changes in 873b9bdbca570d878e5acbd34b40d4b005c72709 and polished it in 107f38fff9a4d20504be9356f36f86190d095dc8.

In the future, you can run `./gradlew format` to update the formatting in your changes.

**Pull request closed without merging**
