### PR TITLE
Fix <headers defaults-disabled=true> with no children

### PR DESCRIPTION
**Pull request by frickjack**
The online docs
     http://docs.spring.io/spring-security/site/docs/current/reference/html/headers.html
suggest that

```xml
     <headers defaults-disabled="true"/>
```

ought to disable the default security headers, but the HeaderWriterFilter has an assertion that its header-writer list is non empty.  This patch just changes Assert.notEmpty to Assert.notNull

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@frickjack Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=3986)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=3986) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by frickjack** [comment]
Ugh - the XML was busted in the comment:
    headers defaults-disabled="true"
XML element should disable headers, but the filter is unhappy ...

**Comment by pivotal-issuemaster** [comment]
@frickjack Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=3986)!

**Comment by rwinch** [comment]
Given the lack of response for submitting an updates PR, I went ahead and fixed as I discussed in my previous comment.

Thanks again for submitting the PR and the issue. It is only through community members like you (that take the time to report issues) that we are able to make Spring better!

**Pull request closed without merging**
