### PR TITLE
Introduced new AbstractUsernamePasswordAuthenticationFilter

### PR DESCRIPTION
**Pull request by marceloverdijk**
I've created a new AbstractUsernamePasswordAuthenticationFilter.
AbstractUsernamePasswordAuthenticationFilter allows more easily custom username/password based authentication scenario's.
Implmenetors can e.g. use form submission data, request headers or a json payload.

The existing UsernamePasswordAuthenticationFilter is now extending this new  AbstractUsernamePasswordAuthenticationFilter, but API wise it's unchanged and supports exactly what it does now.

So what this AbstractUsernamePasswordAuthenticationFilter provides for me at the end is an easy way to create my custom JsonUsernamePasswordAuthenticationFilter.

What do you think?

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! I want to let you know I did see this. Right now I'm very heads down on getting 4.0 out the door. I will revisit this once 4.0 is GA.

**Comment by marceloverdijk** [comment]
OK thanks! If you are interested to take this on board, it might be useful to also merge it into 3.2 line.
I'm currently developing a small Spring Security extension which provides JWT integration via simple filter (without OAuth) which I will publish on github. This AbstractUsernamePasswordAuthenticationFilter would come in handy then.

**Comment by pivotal-issuemaster** [comment]
@marceloverdijk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by marceloverdijk** [comment]
Signed!

**Comment by pivotal-issuemaster** [comment]
@marceloverdijk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@marceloverdijk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by rwinch** [comment]
I'm closing this as won't fix as this doesn't add much value over just extending `UsernamePasswordAuthenticationFilter ` and adds additional noise to the APIs and complicates the object hierarchy.

**Pull request closed without merging**
