### PR TITLE
Fire a LogoutSuccessEvent in case of logout

### PR DESCRIPTION
**Pull request by mdeinum**
This commit introduces a LogoutSuccessEvent which is
fired upon logout. Both the LogoutFilter and ConcurrentSessionFilter
fire the event to indicate a session ended forcefully or not.

Closes: gh-2900

- [X] I have signed the CLA

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR @mdeinum!

Perhaps this makes more sense implemented as a LogoutHandler? This would allow the logic to be reused. Thoughts?

**Comment by mdeinum** [comment]
I was thinking about that as well. However I wanted to make sure that the event was fired even if someone would register his own `LogoutHandler`s. As long as we can make sure that this one is always part of the full collection of `LogoutHandler`s I don't see the problem with that.

**Comment by rwinch** [comment]
I think that we should use LogoutHandler as the preferred approach. 

What might be good to do is also provide a `CompositeLogoutHandler` implementation which iterates over a bunch of `LogoutHandler` instances. Then anything using a collection of `LogoutHandler`'s could create an instance of `CompositeLogoutHandler`. I created a distinct issue for this #3895

**Comment by kazuki43zoo** [comment]
Hi @rwinch, 
I think `LogoutHandler` has role for customizing a web layer processing (clear http session, clear any cookies, etc... ). On the other hand, `LogoutSuccessEvent` has role for customizing a domain layer processing(not depends on the web layer).
I prefer to add a new event to notify logout success to any spring bean. 
What do you think ?

Note: I've submit a same PR on #3883.

**Comment by rwinch** [comment]
@kazuki43zoo I'm not sure I understand your comment or perhaps you didn't understand mine.

My suggestion was that LogoutFilter and ConcurrentSessionFilter should not fire the event directly. Instead, the LogoutSuccessEvent will be fired by a LogoutHandler. This allows the logic for firing of the event to be reused.

I think we agree that LogoutSuccessEvent should not depend on the web layer. The only difference is where the event should be fired from.

**Comment by kazuki43zoo** [comment]
@rwinch Thanks for your comment!!

I understood your opinion!!
I agree with you.

**Comment by mdeinum** [comment]
@rwinch What you describe was actually more or less my initial attempt :) (with a `CompositeLogoutHandler`. I can refactor the code. Would then also refactor the array/collection of `LogoutHandler`s in the `LogoutFilter` and `ConcurrentSessionFilter` (and maybe other places) to use this `CompositeLogoutHandler`?

I can have a look at that issue and also refactor this into using a `LogoutHandler` instead of directly firing events (I might even still have that in my local history).

**Pull request closed without merging**
