### PR TITLE
Support new event for indicates logout success

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've fixed gh-3307.
This PR does not support a functionality for notifying a expired or not.
Please review this.

---

Related PRs : #3883

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
I've fixed some conflicts.

**Comment by okohub** [comment]
+1

**Comment by jzheaux** [comment]
@kazuki43zoo I realize this is an old PR, but I'd like to see if you are still interested in getting it into a mergeable state. Would you like to rebase, and I'll work with you to get it to where it needs to be?

**Comment by eleftherias** [comment]
Closing because a very similar PR gh-7306 already fixed this issue.

**Pull request closed without merging**
