### PR TITLE
Change constant SAVED_REQUEST to public

### PR DESCRIPTION
**Pull request by quaff**
Application code can refer to it.

### CODE REVIEW

**Comment by rwinch** [comment]
Why do you need to refer to it? You can use the `RequestCache` to read and write the value.

**Comment by quaff** [comment]
It's a trivial request, If you think not worthy, never mind.
I'm implementing my own `HttpSession`, I don't want SAVED_REQUEST trigger setDirty(true), code like this:
```
	@Override
	public Object getAttribute(String key) {
		return attrMap.get(key);
	}

	@Override
	public void setAttribute(String key, Object object) {
		attrMap.put(key, object);
		if (!key.equals("SPRING_SECURITY_SAVED_REQUEST"))
			setDirty(true);
	}
	@Override
	public void removeAttribute(String key) {
		attrMap.remove(key);
		if (!key.equals("SPRING_SECURITY_SAVED_REQUEST"))
			setDirty(true);
	}
```

**Comment by rwinch** [comment]
I'm closing this because it unnecessarily breaks encapsulation. Instead you can set the attribute on the request cache and ensure the value you set it to matches that of the custom HttpSession.

**Comment by quaff** [comment]
@rwinch How to autowire my own `RequestCache` implementation using xml configuration? It doesn't works even if mark it as primary, thanks a lots.

**Comment by rwinch** [comment]
See https://docs.spring.io/spring-security/site/docs/5.1.x/reference/htmlsingle/#nsa-request-cache-attributes

**Comment by quaff** [comment]
👍

**Pull request closed without merging**
