### PR TITLE
Make CachingUserDetailsService Public

### PR DESCRIPTION
**Pull request by ir73**
- changed default to public constructor in CachingUserDetailsService

Changed based on the comments in this thread https://github.com/spring-projects/spring-security/issues/4139

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ir73 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6196)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6196) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ir73 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6196)!

**Comment by rwinch** [comment]
Thank you for the PR @ir73!

Can you please update the commit message to align with [the Spring Security conventions](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#format-commit-messages)?

**Comment by ir73** [comment]
sure, hope it looks better now.

**Comment by ir73** [comment]
@rwinch anything else I could help to get this PR merged?

**Comment by rwinch** [comment]
@ir73 Thanks for the nudge. Somehow I had missed your comment from the other day. This is now merged into master. Thanks again for your contribution! It is great to see community members like you helping to make Spring better. I hope to see contributions from you again :smile:

**Pull request merged**
