### PR TITLE
Update ldap/src/main/java/org/springframework/security/ldap/SpringSecuri...

### PR DESCRIPTION
**Pull request by redzedi**
...tyLdapTemplate.java

making these fields protected help in easily overriding this class that provides lots of useful functionality otherwise. In my case i required a search method that would return dns for all entries that match the given search criteria. An incredibly versatile method will be one that takes in a contextMapper in addition to base , filter, params etc.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@redzedi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@redzedi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=27) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by eleftherias** [comment]
@redzedi Can you please provide more details about the goals of this PR?  
Given that subclasses can easily create their own logger, and that there is already a `setSearchControls` method, I don't see the value in making those fields protected.

**Comment by eleftherias** [comment]
Closing due to inactivity and lack of feedback.
A workaround is provided in the previous comment.
Please let us know if the issue persists and we will re-open it.

**Pull request closed without merging**
