### PR TITLE
Remove Invalid WebMvcConfigurer from Sample Documentation

### PR DESCRIPTION
**Pull request by adamzimny**
Obvious Fix
Fixes gh-6809

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! Since this is the hello world (minimal sample) we can remove `extends WebSecurityConfigurerAdapter` as well. Can you please update the PR to do that?

**Comment by adamzimny** [comment]
Hi Rob,

you are right that `extends WebSecurityConfigurerAdapter` is not needed in the example itself. But if you read on and get to chapter 6.3 (and 6.4 and 6.5) then these chapters refer to the hello world example and explain why we extend from WebSecurityConfigurerAdapter and how it's functionality can be used.
This is actually how I came across the issue, I copy/pasted the hello world code snippet to my application, then continued reading and then at chapter 6.3 things no longer made much sense.

**Comment by rwinch** [comment]
I think that along with that we should update the documentation to explain that when extending `WebSecurityConfigurerAdapter` is needed too (i.e. when we need to modify the default behavior of web based security).

**Comment by adamzimny** [comment]
This is explained in chapters 6.2 - 6.5. You may be right that this documentation fragment is not perfect and it could use some refactoring. But the intention of this patch is just to fix an obvious bug - wrong class name used in the example.

**Comment by pivotal-issuemaster** [comment]
@adamzimny Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6850)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6850) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@adamzimny Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6850)!

**Comment by jzheaux** [comment]
Closed in favor of 362356d

**Pull request closed without merging**
