### PR TITLE
Add @Transient to OAuth2IntrospectionAuthenticationToken

### PR DESCRIPTION
**Pull request by huytn12**

### CODE REVIEW

**Comment by jzheaux** [comment]
@huytn12 Thanks for the update! I have two questions:

- Are you taking a look at why the build is failing?
- Will you please also squash your commits into one commit, in preparation for merging?

Of course, let me know if you'd like help with either of these.

**Comment by huytn12** [comment]
@jzheaux Sorry for being delayed. 
I looked at the build log and noticed that the build failed at 

> > Task :spring-security-web:jacocoTestReport
[ant:jacocoReport] Classes in bundle 'spring-security-web' do no match with execution data. For report generation the same class files must be used as at runtime.
[ant:jacocoReport] Execution data for class org/springframework/security/web/debug/Logger does not match.

> Task :spring-security-web:check
> Task :spring-security-web:build

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-security-config:compileTestJava'.
> Compilation failed; see the compiler error output for details.

So I believe there's something wrong when I added new test. I'm not so sure how to fix the issue so It would great if you could help me with it. 
And yes, I will squash my commits into one. 
Thanks

**Comment by jzheaux** [comment]
When I build your branch, the output shows this error:

```bash
/home/jzheaux/dev/spring-projects/spring-security/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java:571: error: cannot find symbol
        assertThat(result.getRequest().getSession(false)).isNull();
```

Does that give you enough to go off of?

**Comment by jzheaux** [comment]
Also, @huytn12, will you please update the title and description of this PR so it reflects the issue you are solving? Maybe something like "Add @Transient to OAuth2IntrospectionAuthenticationToken".

**Comment by huytn12** [comment]
@jzheaux I updated the test and now the build failed again with different error. I look at the log file and found this 

> [ant:jacocoReport] Classes in bundle 'spring-security-web' do no match with execution data. For report generation the same class files must be used as at runtime.
[ant:jacocoReport] Execution data for class org/springframework/security/web/debug/Logger does not match.

I think the the execution data for class doesn't exist. I'm not so sure how to fix this issue. Could you give me some help?

**Comment by jzheaux** [comment]
When I compile your branch locally, I get:

```bash
/home/jzheaux/dev/spring-projects/spring-security/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java:569: error: incompatible types: ResultActions cannot be converted to MvcResult
                                .andExpect(content().string("test-subject"));
```

Are you able to run the build locally? 

Are you using an IDE? It should be able to highlight these compiler errors for you before you push.

If not, then I recommend starting fresh. Get the library running in your IDE. That way, you'll be able to run the test yourself and see whether it passes or fails before pushing.

**Comment by jzheaux** [comment]
@huytn12 is this something you are still interesting in contributing?

**Comment by florian42** [comment]
@jzheaux  if @huytn12 isn’t interested anymore I’d love to finish the test case and create a new pr.

**Comment by jzheaux** [comment]
@florian42 thank you, that'd be great. Please also link your PR to https://github.com/spring-projects/spring-security/issues/6829, the related issue.

**Comment by jzheaux** [comment]
@florian42 is this still something you'd like to contribute a PR for?

**Comment by florian42** [comment]
Hi yes, didn’t get a notification. Will do it tomorrow 👍

**Pull request closed without merging**
