### PR TITLE
Extended testing api for tests

### PR DESCRIPTION
**Pull request by sandmannn**
This is the first PR to address extension of testing API as described in https://github.com/spring-projects/spring-security/issues/6896

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sandmannn Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6923)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6923) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sandmannn Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6923)!

**Comment by jzheaux** [comment]
@sandmannn Thanks for the PR! Would you please add a unit test that proves that the method works?

Also, will you please squash your commits so that you just have one commit in the PR?

**Comment by sandmannn** [comment]
@jzheaux thanks for the review, I squashed commits and added a single unit test. Please suggest in case some additional testing scenarios are desired.

**Comment by jzheaux** [comment]
Just one more thing, @sandmannn. Would you please add the ticket number into your commit message [like so](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#format-commit-messages).

**Comment by sandmannn** [comment]
> Just one more thing, @sandmannn. Would you please add the ticket number into your commit message [like so](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#format-commit-messages).

Done, please review corrected commit message

**Comment by jzheaux** [comment]
Could you please change it to say "Fixes:  gh-6896". 

The reason for that is that we use "Issue: gh-6896" to indicate that a given commit contributes to an issue but does not necessarily fix it. Since your commit completely fixes the issue, it should say "Fixes: gh-6896".

**Comment by sandmannn** [comment]
> Could you please change it to say "Fixes: [gh-6896](https://github.com/spring-projects/spring-security/issues/6896)".
> 
> The reason for that is that we use "Issue: [gh-6896](https://github.com/spring-projects/spring-security/issues/6896)" to indicate that a given commit contributes to an issue but does not necessarily fix it. Since your commit completely fixes the issue, it should say "Fixes: [gh-6896](https://github.com/spring-projects/spring-security/issues/6896)".

actually I am not sure if my commit completely fixes the issue, as the fix for reactive client is still pending to be added in separate PR. Should I still use `Fixes`?

**Comment by jzheaux** [comment]
Good point, @sandmannn. This is now merged into `master`.

Would you like to provide a PR for the reactive equivalent?

**Comment by sandmannn** [comment]
Thanks for merging. Yes, I already started looking into code. Will create a PR soon.

**Pull request merged**
