### PR TITLE
Remove dependency on commons-codec by using java.util.Base64 (for 5.8.x)

### PR DESCRIPTION
**Pull request by j3graham**
gh-11318

Replace commons-codec Base64 with `java.util.Base64`

### CODE REVIEW

**Comment by jzheaux** [comment]
@j3graham, is there some difficulty you are having with running the build locally? I'd be happy to help you work through it. Committing only after you have a clean local build helps the PR process go a little faster.

**Comment by j3graham** [comment]
I don't understand why I'm having this much trouble. I have in fact been running builds. Initially I wasn't carefully running clean builds, so that may have given me the impression that I had fixed everything.

I expect it's too late now, but in hindsight, I was unable to find working instructions to configure IntelliJ to follow the formatting standards, and the only way I was able to find the rules for import ordering was by looking at the code for the spring-javaformat plugin.

I'm also a little suspicious of the interaction between the gradle build cache and Checkstyle.

This latest push I cloned to a new directory, deleted the gradle build cache, did a clean build and it's happy.

At this point I've spent more time trying to get the formatting right than it took to make the original change. My apologies for making you spend time on it too.

**Comment by jzheaux** [comment]
@j3graham, gotcha. Sorry to hear that the formatting has been a pain point.

If it helps, here is my IntelliJ import order setup:

```
import java.*
<blank line>
import javax.*
<blank line>
import jakarta.*
import all other imports
<blank line>
import org.springframework.*
<blank line>
import static all other imports
```

At this point, it looks like the build is passing; thanks for working on getting past that hurdle.

In preparation for merging, then, will you please squash your commits?

**Comment by j3graham** [comment]
@jzheaux Hopefully that does it. Thanks for the help.

**Comment by jzheaux** [comment]
Just one more thing, @j3graham, and then we're ready. Will you please include the issue number in the commit message? Like this:

```
Remove dependency on commons-codec by using java.util.Base64 

Closes gh-11318
```

This assists with backporting among other things.

**Comment by j3graham** [comment]
Message updated.

**Pull request merged**
