### PR TITLE
OAuth2LoginSpec discovers ReactiveOAuth2AccessTokenResponseClient @bean

### PR DESCRIPTION
**Pull request by d3jie**
Fixes: gh-6477

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@d3jie Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6587)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6587) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@d3jie Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6587)!

**Comment by jgrandja** [comment]
Thanks for the PR @d3jie! I applied some minor polish to the commit and merged to master!
Thanks again and we look forward to your next contribution :)

**Comment by d3jie** [comment]
Thanks @jgrandja. Can you tell me about the minor polish you applied? Maybe I can learn a thing or two. :)

**Comment by jgrandja** [comment]
Sure @d3jie 

In `createDefault()`, you had...


```java
ReactiveAuthenticationManager result = new OAuth2LoginReactiveAuthenticationManager(getAccessTokenResponseClient(), getOauth2UserService());

...

OidcAuthorizationCodeReactiveAuthenticationManager oidc = new OidcAuthorizationCodeReactiveAuthenticationManager(getAccessTokenResponseClient(), getOidcUserService());
```

I changed it to...

```java
ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> client = getAccessTokenResponseClient();

ReactiveAuthenticationManager result = new OAuth2LoginReactiveAuthenticationManager(client, getOauth2UserService());

...

OidcAuthorizationCodeReactiveAuthenticationManager oidc = new OidcAuthorizationCodeReactiveAuthenticationManager(client, getOidcUserService());
```

So we re-use the `client` instance in both managers if the `@Bean` **was not** provided.


And in`OAuth2LoginTests`, I renamed the `@Bean` method from `oAuth2AccessTokenResponseClient()` to `accessTokenResponseClient()`. We typically don't prefix member variables or method declarations with `oauth2*`.

Those were the only 2 changes.

**Comment by d3jie** [comment]
@jgrandja I can see what you did there. It didn't occur to me that I could do it this way. Many thanks. Looking forward to the next. 👍

**Pull request closed without merging**
