### PR TITLE
Update to Gradle 5.0

### PR DESCRIPTION
**Pull request by dbuos**
Change project's gradle version to 5.0, this requires to make some minor
adjustments.

Fixes: gh-6148

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dbuos Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6197)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6197) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dbuos Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6197)!

**Comment by rwinch** [comment]
Thanks for the PR @dbuos! This is now merged into master!

**Comment by raphaelDL** [comment]
I'm trying to build the project locally and sometimes I get the java out of memory exception, I'm not sure if this has something to do. I see that there's a memory limit set

I took a look at: https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#rel5.0:default_memory_settings

when running: `./gradlew clean build integrationTest`

I've got messages like:
```
Execution failed for task 
Java heap space
```
and

```
Expiring Daemon because JVM Tenured space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
```

I don't know, what do you guys think? did it happen to you?

**Comment by rwinch** [comment]
@raphaelDL Thanks for reaching out. I wonder if there is a memory leak somewhere. If you use the `--no-daemon` does it ever run out of memory?

**Pull request merged**
