### PR TITLE
Saml2AuthenticationRequestContext should be extendible #8356

### PR DESCRIPTION
**Pull request by shazin**
Fixes issue #8356

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks, @shazin! Would you please squash your commits and format it to look something like:

```
Open Saml2AuthenticationRequestContext

Fixes gh-8356
```

For extra context, please see the contribution guidelines for [squashing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#squash-commits) and [formatting](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#format-commit-messages) commits.

**Comment by shazin** [comment]
I tried squashing but it doesn't seem to show any commits to squash.

**Comment by jzheaux** [comment]
No problem, @shazin, let's try this. 

Can you rebase your branch with `master`? For example, if you've defined the `spring-projects/spring-security` upstream as `spring-projects` and your own fork as `origin`, you can do this:

```java
git checkout master
git reset --hard spring-projects/master
git push origin +master
git checkout gh-8356
git rebase master
```

At that point, a `git log master..` should only return the commits on the `gh-8356` branch that you've committed, and it won't have any merge commits.

At that point, doing something like `git rebase -i gh-8356~x` (where x is the number of commits to view) should show you a set of commits that makes sense to squash.

Once the commit list on the `gh-8356` branch looks like you want it to, then you can do `git push origin +gh-8356` and GitHub will update the PR here.

**Comment by shazin** [comment]
I Followed the instruction and now only one commit is visible. Thanks

**Comment by jzheaux** [comment]
Awesome, @shazin! This is now merged into `master` via 4e5a3a76cd644dbaf4d54d2c4b921d67476db7d7

**Pull request closed without merging**
