### PR TITLE
Add support for AuthnRequestsSigned setting

### PR DESCRIPTION
**Pull request by 1livv**
closes gh-12604

### CODE REVIEW

**Comment by 1livv** [comment]
Would it be possible to have this merged in the 5.8.x alongside main even it's a new feature ? We're still using spring 5

**Comment by jzheaux** [comment]
Sorry, @1livv, that I missed your earlier comment about 5.8. Generally, our policy is to only backport bugs to 5.8.

In the meantime, I believe you have the option to override the provider setting in `RelyingPartyRegistration`. Have you already tried that as a workaround?

**Comment by 1livv** [comment]
Thanks for the workaround @jzheaux that works ? Do I need to make my PR against main now ?

**Comment by jzheaux** [comment]
Yes, @1livv, it would be best to rebase on `main`.

**Comment by 1livv** [comment]
@jzheaux  rebased it

**Pull request merged**
