### PR TITLE
Updated Spring Boot version from 2.1.0.M4 to 2.1.0.RELEASE

### PR DESCRIPTION
**Pull request by raphaelDL**
From `https://github.com/spring-projects/spring-security/issues/6082`

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR @raphaelDL! 

It appears the [build failed](https://travis-ci.org/spring-projects/spring-security/builds/454746281?utm_source=github_status&utm_medium=notification). This was because I missed a step. Sorry about that.

Can you please update any references of thymeleaf-extras-springsecurity4 to thymeleaf-extras-springsecurity5? Once you have done that the build will pass (I verified locally).

If you are using a Linux based system you can use [ripgrep](https://github.com/BurntSushi/ripgrep) along with the following to do the find/replace.

```
rg -l thymeleaf-extras-springsecurity4 | xargs sed -i -e 's/thymeleaf-extras-springsecurity4/thymeleaf-extras-springsecurity5/'
```

You can also refer to the following locations if you cannot use the command above:

```
samples/boot/helloworld/spring-security-samples-boot-helloworld.gradle
10:	compile 'org.thymeleaf.extras:thymeleaf-extras-springsecurity4'

samples/boot/oauth2login-webflux/spring-security-samples-boot-oauth2login-webflux.gradle
11:	compile 'org.thymeleaf.extras:thymeleaf-extras-springsecurity4'

samples/boot/oauth2login/spring-security-samples-boot-oauth2login.gradle
11:	compile 'org.thymeleaf.extras:thymeleaf-extras-springsecurity4'

samples/boot/oauth2webclient-webflux/spring-security-samples-boot-oauth2webclient-webflux.gradle
9:	compile 'org.thymeleaf.extras:thymeleaf-extras-springsecurity4'

samples/boot/oauth2webclient/spring-security-samples-boot-oauth2webclient.gradle
12:	compile 'org.thymeleaf.extras:thymeleaf-extras-springsecurity4'

docs/guides/src/docs/asciidoc/helloworld-boot.asc
35:<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org" xmlns:sec="http://www.thymeleaf.org/thymeleaf-extras-springsecurity4">

samples/boot/helloworld/src/main/resources/templates/index.html
2:<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org" xmlns:sec="http://www.thymeleaf.org/thymeleaf-extras-springsecurity4">

docs/guides/src/docs/asciidoc/_hello-includes/secure-the-application-boot.asc
29:	<artifactId>thymeleaf-extras-springsecurity4</artifactId>	<1>

samples/boot/oauth2login/src/main/resources/templates/index.html
2:<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org" xmlns:sec="http://www.thymeleaf.org/thymeleaf-extras-springsecurity4">

samples/boot/oauth2webclient-webflux/src/main/resources/templates/index.html
2:<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org" xmlns:sec="http://www.thymeleaf.org/thymeleaf-extras-springsecurity4">

samples/boot/oauth2webclient/src/main/resources/templates/index.html
2:<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org" xmlns:sec="http://www.thymeleaf.org/thymeleaf-extras-springsecurity4">
```

If you want to double check you can run the following after you have made the changes:

```
./gradlew build
```

Once you are done you can amend the commit and force push to your branch to update the PR and trigger another build. If you need help with any of this, please let me know.

**Comment by raphaelDL** [comment]
Thank you, I know... I'm about to send my commit, just waiting for the tests to finish :)

**Comment by raphaelDL** [comment]
Sorry I was trying something else before pushing my commit, all tests take 13mins in my machine. I ran them all three times 🙃

**Comment by raphaelDL** [comment]
@rwinch CI is running now

**Comment by raphaelDL** [comment]
@rwinch it’s ready  :)

**Comment by rwinch** [comment]
Thanks @raphaelDL! This is now merged into master :smile:

**Comment by rwinch** [comment]
Thanks for the heads up @raphaelDL! This will be addressed in #5026 It also overlaps with us rewriting the docs for 5.2 #2567

**Pull request merged**
