### PR TITLE
Metadatasource's attributes default value is an empty collection, not null value.

### PR DESCRIPTION
**Pull request by gcernier-amadeus**
As it's specified in the `SecurityMetadataSource` interface's Javadoc.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gcernier-amadeus Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=4898)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=4898) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gcernier-amadeus Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=4898)!

**Comment by gcernier-amadeus** [comment]
It has been validated that changes brought by this pull-request build correctly.
Build issues are the existing ones on the `master` branch.

**Comment by rwinch** [comment]
Thanks for the PR @gcernier-amadeus!

From the [Javadoc](https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/api/org/springframework/security/access/SecurityMetadataSource.html#getAllConfigAttributes--):

> the ConfigAttributes or null if unsupported

The return of `null` is intentional because validation of the attributes is not supported

Since this works as documented, I'm closing this as invalid

**Comment by gcernier-amadeus** [comment]
Hello @rwinch,

That's indeed the Javadoc for `getAllConfigAttributes()` but not for [`getAttributes()`'s](https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/api/org/springframework/security/access/SecurityMetadataSource.html#getAttributes-java.lang.Object-):

> Returns: `the attributes that apply to the passed in secured object. Should return an empty collection if there are no applicable attributes.`

I went indeed too far as `getAllConfigAttributes()`'s behaviour should not be modified, but `getAttributes()`'s one should be. What do you think of re-opening the pull-request after I reduce the change to `getAttributes()`'s?

**Pull request closed without merging**
