### PR TITLE
gh-14525 Extend `org.springframework.security.web.authentication.logo…

### PR DESCRIPTION
**Pull request by aspan**
…ut.LogoutFilter` so that the relying party initiated logout filter is ordered before the existing `org.springframework.security.web.authentication.logout.LogoutFilter`

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks for the fix, @aspan. Are you able to rebase this off of `5.8.x` so that I can forward port it to the other branches more easily?

**Comment by jzheaux** [comment]
And, could you please do two more things to simplify future maintenance:

- Run `./gradlew format` to align your changes with the project formatting standards
- Change the commit to be formatted similar to this:

```
Saml2 LogoutFilter Is Placed Before Common LogoutFilter

Closes gh-14525
```

The main thrust is the title should be short and there should be the phrase "Closes gh-14525" in the description.

**Comment by aspan** [comment]
Reformatted code and changed the commit message. Also made a separate pull request for the 5.8.x branch.

**Comment by jzheaux** [comment]
Awesome, thanks @aspan! I'll close this in favor of https://github.com/spring-projects/spring-security/pull/14549.

**Pull request closed without merging**
