### PR TITLE
Add AuthenticationConverter interface

### PR DESCRIPTION
**Pull request by edeandrea**
- Adding an `AuthenticationConverter` interface
- Retro-fitting `ServerFormLoginAuthenticationConverter`, `ServerHttpBasicAuthenticationConverter`,
and `ServerOAuth2LoginAuthenticationTokenConverter` to implement AuthenticationConverter
- Deprecate existing `AuthenticationWebFilter.setAuthenticationConverter`
and add overloaded one which takes `AuthenticationConverter`

Fixes gh-5338

### CODE REVIEW

**Comment by edeandrea** [comment]
Hi @rwinch just a gentle ping to see if this PR needs any more polish or anything.

**Comment by edeandrea** [comment]
Apologies I think I messed something up here. I think I accidentally merged instead of rebasing. Maybe I should start over with a different PR?

**Comment by rwinch** [comment]
You should be able to recover from the merge by looking at your reflog. Alternatively, you can save this work in another branch temporarily. Note the sha ids of the commits you made. Come back to this branch and do a `git reset --hard origin/master`. Then do a `git cherry-pick <sha-id>` for each commit you had. Then you can do a `git push -f` to the branch this PR is on to update the PR.

If you do want to start a new PR, please close this one out.

**Comment by edeandrea** [comment]
Re-done with #5689

**Pull request closed without merging**
