### PR TITLE
ABAC support for spring security

### PR DESCRIPTION
**Pull request by simplicii**
ABAC is a standard published by NIST (US National Institute od Standarts and Technology) in cooperation with industry and universities.
ABAC grants access based on user attributes and policies.

Updated spring manual: https://github.com/simplicii/spring-abac-sample/blob/master/spring-security-reference.pdf

Wikipedia: https://en.wikipedia.org/wiki/Attribute-Based_Access_Control
NIST: http://csrc.nist.gov/projects/abac/

This is the implemenation for #4276

### CODE REVIEW

**Comment by rwinch** [comment]
@simplicii Thank you for the PR! 

Can you elaborate how this will work with large data sets? I'm curious what your real world experience is when using ABAC is? Historically I have never been able to use authorization which happens after the database query because it will not perform. Obviously Spring Security ACL behaves the same way, but it is too late to change that.

It may be worth mentioning that rather than extending the expression root, I typically recommend users to [refer to another bean](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#el-access-web-beans) in the expression using `@beanName.methodThatReturnsBoolean(...)`.

**Comment by simplicii** [comment]
As you said, acl behaves unfortunately the same way. Thats why I did it this way too.
For @Pre operation it should be no problem and the PostFilter will have the same issue than the ACL.
Fortunately I only used ACL on MickeyMouse projects so far. 
I think I would anyway use Native Sql queries to perform ACL on bigger data sets to let DB optimize it.
Honestly, your proposal to use [refer to another bean](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#el-access-web-beans) . Might be more flexible anyway.  Possible that this is obsolete from a different perspective.

The Idea to write spring-abac was to have something inbetween ROLES and ACL.

**Comment by rwinch** [comment]
Thank you for your response.

I'm somewhat hesitant to add support for something that would not work on large data sets. I realize that Spring ACL has the same limitations, but that decision was made before I had a vote.

> Honestly, your proposal to use refer to another bean might be more flexible anyway. Possible that this is obsolete from a different perspective.

This is probably the best option. Perhaps we need to make this more obvious in the documentation that it is available.

**Comment by simplicii** [comment]
Makes sense if you could update the documentation to make it more obvious.
I will delete my PR for now and see how that goes.

**Comment by ugultopu** [comment]
What is the end decision here? Will Spring Security have ABAC? Or should we simulate ABAC using SpEL? Will Spring Security have XACML support?

**Comment by rwinch** [comment]
@ugultopu For now users should leverage SpEL expressions. If someone can describe a way to use ABAC in a large scale system, we can reconsider adding ABAC support.

**Comment by Kiddinglife** [comment]
[](https://www.openpolicyagent.org/)

**Pull request closed without merging**
