### PR TITLE
Prevent JwtAuthenticationProvider from setting authentication details when jwtAuthenticationConverter returned an authentication instance with non null details

### PR DESCRIPTION
**Pull request by ch4mpy**
This could fix gh-11822

### CODE REVIEW

**Review by sjohnr — CHANGES_REQUESTED** [review]
Thanks @ch4mpy! It would be helpful if you could add a test that ensures the provider is not overwriting details.

**Comment by ch4mpy** [comment]
@sjohnr done

**Comment by ch4mpy** [comment]
@sjohnr anything more needed on this PR?

**Comment by sjohnr** [comment]
@ch4mpy, thanks for asking! I don't think so, but I'm heads down on a few other things and will circle back to this a bit later.

**Review by sjohnr — CHANGES_REQUESTED** [review]
@ch4mpy, when thinking more about this PR, we will need to make an adjustment. For the 5.8/6.0 releases, we are aiming to provide an upgrade to 5.8 that contains no breaking changes. Anything that breaks passivity would require a configuration option that allows users to opt-in to the change to test their compatibility in 5.8, so that an upgrade to 6.0 (where the change is the default) is seamless.

This change is technically a breaking change, as it would have been possible previously to return a non-null `details` which is overridden in the filter and will no longer be. Because the details can be used for things like authorization, we should not include this change in 5.8 without allowing it to be opt-in.

I think the simplest change is to move this PR to be based on 6.0. Can you make this change? I've also added minor suggestions below.

**Comment by ch4mpy** [comment]
@sjohnr rebased on main and updated copyright.

P.S.
Well, the scenario in which one sets detail in authentication converter and this details being overriden by the framework is the exact one a team I know went through and none expected to have details "lost". Reason for me opening the ticket as a "bug".  Of course, whith my recent contribution, it didn't take me long to spot their problem and provide them with a work around.

I hadn't considered it an expected "feature", which is why I initialy based the PR on 5.8

**Comment by ch4mpy** [comment]
Any plan to merge this sometime? 
This would allow me to use immutable `Authentication` implementations in servlets with JWT decoder (can currently do it in reactive apps only).

**Comment by sjohnr** [comment]
Hi @ch4mpy!

> Any plan to merge this sometime?

Apologies, I wasn't able to circle back to this in time for RC1. I'm going to schedule this for 6.1 as I'd prefer to hold off on any code enhancements in the RC phase of 6.0. I'll merge this after the GA release.

**Comment by sjohnr** [comment]
This is merged via 7ad4ebd07ad0c3c8a507cf68bb35308b6595042a

**Pull request closed without merging**
