### PR TITLE
add hasAnyRole method in AuthorizePayloadsSpec.Access

### PR DESCRIPTION
**Pull request by matedeilo**
See [gh-7437](https://github.com/spring-projects/spring-security/issues/7437)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@matedeilo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=7453)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=7453) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@matedeilo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=7453)!

**Comment by eddumelendez** [comment]
@rwinch do you think this PR makes sense and can be merged anytime soon?

**Comment by rwinch** [comment]
Thanks @matedeilo! This is now merged into master

**Pull request merged**
