### PR TITLE
DigestAuthenticationFilter decodes nonce only once

### PR DESCRIPTION
**Pull request by amarkevich**
trivial

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@amarkevich Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8455)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=8455) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@amarkevich Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8455)!

**Comment by rwinch** [comment]
Thanks for the Pull Request! This is now merged into master :smile:

**Comment by jgrandja** [comment]
@amarkevich It looks like this wasn't actually merged back in May 2020. It is now merged into main. Thank you!

**Pull request closed without merging**
