### PR TITLE
The HttpHeader's ContentLength is a byte unit

### PR DESCRIPTION
**Pull request by XYUU**
Such as
image
view source:
image

### CODE REVIEW

**Comment by jzheaux** [comment]
Hey, @XYUU, nice catch! Would you be able to add a test that confirms the working behavior, too? (One that breaks without your fix and works with it.)

**Comment by jgrandja** [comment]
@XYUU I noticed your commits have changes not related to this issue. There are quite a few additions/changes to the OAuth 2.0 Login feature. Was your original intention to submit these changes via another PR?

**Comment by XYUU** [comment]
OKay，I will resubmit tomorrow, including the content of the unit test.

**Comment by XYUU** [comment]
@jgrandja @jzheaux 
I have resubmitted the PR, hoping to merge with the master.

Implementing OAuth2AccessTokenResponseClient and DefaultOAuth2UserService using RestTemplate 
https://github.com/spring-projects/spring-security/pull/5266

The HttpHeader's ContentLength is a byte unit
https://github.com/spring-projects/spring-security/pull/5261

**Pull request closed without merging**
