### PR TITLE
Add Reactive One-Time Token Login Kotlin DSL Support

### PR DESCRIPTION
**Pull request by CrazyParanoid**
Closes gh-15887

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks, @CrazyParanoid! While we are here, will you please do a quick review on the existing Kotlin documentation samples to ensure that they align with your changes? [Some of them](https://github.com/spring-projects/spring-security/blob/b1ac9bd9bac4ad19ed9f8c5211ce00fd1f0be5a5/docs/modules/ROOT/pages/servlet/authentication/onetimetoken.adoc?plain=1#L133) look like they should be adjusted.

**Comment by jzheaux** [comment]
@CrazyParanoid, I pushed a change to the One-Time Token API that you should apply to this PR. I have a commit on my branch that you are welcome to use if you like: https://github.com/jzheaux/spring-security/commit/32448dbb185153912ec378126f4ad681d4be9d28

**Comment by CrazyParanoid** [comment]
Hi @jzheaux, thanks for your commit. I'll fix the documentation, and I also see that I forgot to add the documentation for Kotlin [here](https://github.com/spring-projects/spring-security/blob/main/docs/modules/ROOT/pages/reactive/authentication/onetimetoken.adoc). I'll try to do it today.

**Comment by CrazyParanoid** [comment]
@jzheaux I tried to eliminate the consequences of renaming the API, perhaps I could have missed something somewhere. Could you please review this PR?

**Comment by jzheaux** [comment]
Thanks for the additional updates, @CrazyParanoid. Are you able to isolate the Kotlin DSL support changes to a separate commit from the rest? That way it's clear in the commit log what was needed for which feature.

**Comment by jzheaux** [comment]
Thanks, @CrazyParanoid! This is now merged into `main`.

**Pull request merged**
