### PR TITLE
SEC-2666 Improve Field Visibility in DefaultMethodSecurityExpressionHandler

### PR DESCRIPTION
**Pull request by kevinconaway**
https://jira.spring.io/browse/SEC-2666

We are extending `DefaultMethodSecurityExpressionHandler` in order provide a custom `SecurityExpressionRoot`.

The base `SecurityExpressionRoot` requires an `AuthenticationTrustResolver` in order for all of the expressions to properly work.

 `DefaultMethodSecurityExpressionHandler` creates an `AuthenticationTrustResolver` but it is marked private and is unavailable to subclasses.  This requires subclasses to duplicate the initialization logic from the parent class.

This PR improves the visibility of the fields in `DefaultMethodSecurityExpressionHandler` from private to protected in order to better support subclasses.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kevinconaway Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by kevinconaway** [comment]
Signed

**Comment by pivotal-issuemaster** [comment]
@kevinconaway Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kevinconaway Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by jgrandja** [comment]
Thanks for your input @kevinconaway. FYI, this design is intended. Class fields tend to be private for the most part but we would consider opening it up to protected access for subclass use. However, another design option we may choose instead is to provide a protected getter/setter while preserving the private member field.

There is a public setter available for your use case:

`public void setTrustResolver(AuthenticationTrustResolver trustResolver)`

So what you can do for your implementation is the following:

```
public class CustomMethodSecurityExpressionHandler extends DefaultMethodSecurityExpressionHandler {

	public CustomMethodSecurityExpressionHandler(AuthenticationTrustResolver trustResolver) {
		setTrustResolver(trustResolver);
	}
}

```

This solution should work for you. I'm going to close this PR. However, if this doesn't address your scenario please let me know and we can figure it out.

**Comment by kevinconaway** [comment]
> However, if this doesn't address your scenario please let me know and we can figure it out.

Unfortunately not.  If I remember the scenario correctly (I've since switched jobs since last year), we were adding a `CustomMethodSecurityExpressionHandler` in order to add new expressions to the default ones like `hasRole`.

This is done by creating a custom `MethodSecurityExpressionRoot` and adding custom methods on that class, similar to [hasAuthority()](https://github.com/spring-projects/spring-security/blob/ce20cfcb9803a6175f6befc9008cadcc4e3b6d72/core/src/main/java/org/springframework/security/access/expression/SecurityExpressionRoot.java#L66) or [hasRole()](https://github.com/spring-projects/spring-security/blob/ce20cfcb9803a6175f6befc9008cadcc4e3b6d72/core/src/main/java/org/springframework/security/access/expression/SecurityExpressionRoot.java#L74).

To instantiate a custom `MethodSecurityExpressionRoot`, you need access to the `trustResolver` and `defaultRolePrefix`: https://github.com/spring-projects/spring-security/blob/ce20cfcb9803a6175f6befc9008cadcc4e3b6d72/core/src/main/java/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandler.java#L77

both of which are private.

What would work is providing getters for those fields or making them protected, not private.

**Comment by jgrandja** [comment]
Gotchya.

My preference would be to expose protected accessors for subclasses rather than expose the members to protected.

Given that you switched jobs a while ago, do you still need a solution for this?

**Comment by jgrandja** [comment]
I've re-opened the PR if you would like to update it as discussed with the protected accessors.
Thanks!

**Comment by kevinconaway** [comment]
@jgrandja committed fixes per our discussion

**Comment by jgrandja** [comment]
Thanks for the PR @kevinconaway. This is now merged to master.

**Pull request closed without merging**
