### PR TITLE
Fix issue#9661 Buffer LEAK detected by ResourceLeakDetector in Authen…

### PR DESCRIPTION
**Pull request by kevinat**
Fix issue#9661 Buffer LEAK detected by ResourceLeakDetector in AuthenticationPayloadExchangeConverter

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kevinat Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9671)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=9671) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kevinat Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9671)!

**Comment by jzheaux** [comment]
Thanks for the PR, @kevinat!

Is there a way this can be tested? One way that comes to mind would be to rework how `AuthenticationPayloadExchangeConverter` internals use `ByteBuf` so that it can be invoked from a test.

For example, you could do:

```java
Authentication authentication(ByteBuf rawAuthentication) {
    try {
        // ...
    } finally {
        rawAuthentication.release();
    }
}
```

And you could add a test that invokes that method and confirms that the ref count is equal to 0.

**Comment by kevinat** [comment]
@jzheaux This might not be the best way to test, cos that rework could break the logic of the  method `Authentication authentication(Map<String, Object> metadata)`, it basically takes a byte array from metadata, returns an Authentication, that is good enough. Break this into two method would make the code looks not that good.

I can reproduce the LEAK through this:

```java
for (int i = 0; i < 100000; i++) { 
    authenticationPayloadExchangeConverter.authentication(metadata);
}
System.gc();
```

but I don't known how to make the assertion, because the leak report is just an error log not an exception.

Any suggestion for this @jzheaux? and is it OK to make unit test like this?

**Comment by jzheaux** [comment]
Thanks for the additional feedback about testing, @kevinat. Calling `System.gc()` is not guaranteed to perform a GC, so let's leave the test out.

Thanks again for the PR! I've merged this in commit 32ac31c101807b3d46a9ba5c875ccbf61998aa5f and will backport it to previous releases.

**Pull request closed without merging**
