### PR TITLE
LDAP Java Config supports GrantedAuthoritiesMapper

### PR DESCRIPTION
**Pull request by dalbrekt**
Associated Jira:
https://jira.spring.io/browse/SEC-2557

I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! Unfortunately this PR brings in a lot of unnecessary commits. Anyway you can fix it to only contain the necessary changes?

**Comment by dalbrekt** [comment]
Oops. Where do the other commits come from? My intention was a pull request for this commit only fe33669. Any ideas on how to solve this?

**Comment by rwinch** [comment]
Thanks for pointing out the specific commit. 

I'm not sure which remotes you have so there may be a few steps that are not necessary, but you can perform the following within your clone of the repository:

```bash
$ git remote add spring-security https://github.com/spring-projects/spring-security.git
$ git remote add dalbrekt https://github.com/dalbrekt/spring-security.git
$ git checkout -b SEC-2577-bak SEC-2577
$ git checkout SEC-2577
$ git reset --hard spring-security/master
$ git cherry-pick fe33669f3890131fdc676a7f0a2def2e3348bf89
$ git push -f dalbrekt SEC-2577
```

Otherwise I can likely perform the changes for you as well.

**Comment by dalbrekt** [comment]
Well if you can help me with this please do so.



___________________________________
Tony Dalbrekt

Phone: +46 (0)70 336 57 54
Email: tony@dalbrekt.com
Skype: tony.dalbrekt

**Comment by pivotal-issuemaster** [comment]
@dalbrekt Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@dalbrekt Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dalbrekt Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by rwinch** [comment]
@dalbrekt Thanks for the PR! This is merged into master via b76e3be8223b415e20ebc74377caeb12b09a2380

**Pull request closed without merging**
