### PR TITLE
Fix typo in SecurityFilterChain documentation (obvious fix)

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@PascalSchumacher Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8670)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=8670) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by PascalSchumacher** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@PascalSchumacher This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by PascalSchumacher** [comment]
This fix is already part of https://github.com/spring-projects/spring-security/pull/8666, therefore I am closing this.

**Pull request closed without merging**
