### PR TITLE
Add marker to make Kotlin DSL type safe

### PR DESCRIPTION
**Pull request by LLabagnara**
Add marker on web server security configuration
to make Kotlin DSL type safe.

Issue gh-8366

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@LLabagnara Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8382)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=8382) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@LLabagnara Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=8382)!

**Comment by LLabagnara** [comment]
Thanks for the review @eleftherias !
Sorry I didn't notice the `Fixes` keyword, I already changed the commit message.

**Comment by eleftherias** [comment]
Thanks for the PR @LLabagnara! This is now merged into master.

**Pull request merged**
