### PR TITLE
Polish MvcRequestMatcher

### PR DESCRIPTION
**Pull request by rwinch**
* Fix `HttpSecurity.requestMatchers().mvcMatcher`
* Add `HttpSecurity.mvcRequestMatcher`

### CODE REVIEW

**Comment by rwinch** [comment]
When we are done we need to merge this into master too. The merge into master will resolve #3974 and #3973

**Comment by jgrandja** [comment]
Please also add a javadoc reference to `{@link #mvcMatcher(String)}}` to the following [line in HttpSecurity](https://github.com/rwinch/spring-security/blob/098ab79938ac93a9dd737e3f78d530df8206e093/config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java#L1198)

**Comment by rwinch** [comment]
@jgrandja 

> Please also add a javadoc reference to {@link #mvcMatcher(String)}} to the following line in HttpSecurity

Thanks! This is now done

**Comment by jgrandja** [comment]
Thanks for the PR @rwinch. This is now merged to master and 4.1.x.

**Pull request closed without merging**
