### PR TITLE
Add try-with-resources to close stream

### PR DESCRIPTION
**Pull request by MeTPP**
Closes Issue gh-9041

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@MeTPP Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9053)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=9053) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by MeTPP** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@MeTPP This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by jzheaux** [comment]
Thanks for the PR, @MeTPP! Will you please amend the commit message to say "Closes gh-9041" instead of "Issue gh-9041"? In this way, GitHub will automatically close the related issue when this PR is merged.

**Comment by MeTPP** [comment]
Thanks. I edited my commit comment and force-pushed

**Comment by jzheaux** [comment]
Thanks, @MeTPP! This is now merged into `master`.

**Pull request merged**
