### PR TITLE
Fix Assertion

### PR DESCRIPTION
**Pull request by Russell-Allen**
Just fixing a trivial copy paste error with the variable name.

### CODE REVIEW

**Comment by marcusdacoregio** [comment]
Thanks for the pr @Russell-Allen. It's nice that you found this error.

Could you please amend your commit message to `Fix Assertion`?

**Comment by Russell-Allen** [comment]
I created the PR within github, and I am (so far) unable to find a way to amend the commit message interactively.  And it looks like I'd have to force push a new message if I pulled the repo down locally ...

Do I need to do the latter?  Any alternative suggestions?

**Comment by marcusdacoregio** [comment]
Force-pushing commits is not a problem on your own branch. You can go ahead and do it so the message becomes more clear.

**Comment by marcusdacoregio** [comment]
Thanks @Russell-Allen, I went ahead and changed the message. This is now merged into `main`.

**Pull request closed without merging**
