### PR TITLE
Update javadoc AuthorizationCodeOAuth2AuthorizedClientProvider

### PR DESCRIPTION
**Pull request by talentedasian**
Update Description of AuthorizationCodeOAuth2AuthorizedClientProvider to avoid confusion.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@talentedasian Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9730)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=9730) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by talentedasian** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@talentedasian This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by talentedasian** [comment]
fixes #9708

**Comment by talentedasian** [comment]
closes #9708

**Comment by jgrandja** [comment]
Thanks for the PR @talentedasian. This is now merged.

FYI, I also updated the javadoc for `AuthorizationCodeReactiveOAuth2AuthorizedClientProvider`.

**Pull request closed without merging**
