### PR TITLE
Add Anonymous Support to AuthenticatedReactiveAuthorizationManager

### LINKED ISSUE #6235: AuthenticatedReactiveAuthorizationManager support for AnonymousAuthenticationToken
### Summary

`AuthenticatedReactiveAuthorizationManager` should filter out anonymous authentication by leveraging `AuthenticationTrustResolver`.

### PR DESCRIPTION
**Pull request by mibo**
Fixes: gh-6235

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR @mibo!

Can you please update the commit message to align with [the Spring Security conventions](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#format-commit-messages)?

Something like 

```
Add Anonymous Support to AuthenticatedReactiveAuthorizationManager

Fixes: gh-6235
```

**Comment by mibo** [comment]
@rwinch I changed the commit message accordingly (and remember it for next time 😄 ).

Hope the way with the _forced-push_ is fine in this case.

Regards, Michael

**Comment by rwinch** [comment]
Thanks @mibo! This is now merged into master

> Hope the way with the forced-push is fine in this case.

Yes. It is your branch so a force push is expected in this case.


Thanks again for contributing to Spring Security! We hope to see additional contributions from you soon!

**Comment by mibo** [comment]
> Thanks again for contributing to Spring Security! We hope to see additional contributions from you soon!

Yes, will do my best to do more contributions  ;o)

**Pull request merged**
