### PR TITLE
Rename SecurityConfig to MySecurityConfig

### PR DESCRIPTION
**Pull request by rehevkor5**
Rename SecurityConfig to MySecurityConfig so that readers do not confuse it with org.springframework.security.access.SecurityConfig.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! I think it may make more sense to use WebSecurityConfig. Can you please update the PR to use that instead?

**Comment by rehevkor5** [comment]
@rwinch I updated it to ```WebSecurityConfig``` as requested.

**Comment by pivotal-issuemaster** [comment]
@rehevkor5 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by rehevkor5** [comment]
@pivotal-issuemaster done

**Comment by rehevkor5** [comment]
@rwinch maybe you can merge this now?

**Comment by pivotal-issuemaster** [comment]
@rehevkor5 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rehevkor5 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by rwinch** [comment]
Thanks for the PR! This is now merged into master via https://github.com/spring-projects/spring-security/commit/9fa2c64737e9e9b50113d2f1fef4c998ed4fa5c5

**Pull request closed without merging**
