### PR TITLE
Enable travis caching

### LINKED ISSUE #3844: Enable caching for travis builds
### Summary

Currently, the travis build does not cache the maven and gradle artifacts from build to build.
Caching is enabled in the travis configuration, but it does not work.

### PR DESCRIPTION
**Pull request by jgoldhammer**
Enable travis caching

Currently, the cache setting in the travis configuration does not work as exptepted.
The reason is that caching only works in container-based configuration.
To enable container-based configuration, we have to set sudo to false.
Additionally, I have included the local maven repository for caching.

fixes #3844 

- [X] I have signed the CLA

### CODE REVIEW

**Comment by jgoldhammer** [comment]
See https://travis-ci.org/spring-projects/spring-security/builds/125432654 for advantage of having a cache in comparison to former builds...

**Comment by jgoldhammer** [comment]
Seems that the sudo false breaks Gradle- I have posted a question in the gradle forum:
https://discuss.gradle.org/t/gradle-travis-sudo-false-leads-to-an-error/17034

**Comment by rwinch** [comment]
@jgoldhammer Thanks again for the PR! Any updates on this?

**Comment by pivotal-issuemaster** [comment]
@jgoldhammer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@jgoldhammer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by rwinch** [comment]
Closing this due to lack of feedback and the build failing. Please send a new PR if you get time to get this working.

PS: We do not want to enable maven local as this tends to cause issues with missing dependencies.

**Pull request closed without merging**
