### PR TITLE
Add explanation for DelegatingAuthenticationFailureHandler

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've applied the [SEC-2835](https://jira.spring.io/browse/SEC-2835) in the reference document.

I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kazuki43zoo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@kazuki43zoo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kazuki43zoo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=207)!

**Comment by rwinch** [comment]
Thanks for the PR @kazuki43zoo! This is now merged into master

**Pull request merged**
