### PR TITLE
Configuration of session management strategies

### PR DESCRIPTION
**Pull request by mdeinum**
This commit adds an ExpiredSessionStrategy for the ConcurrentSessionFilter
analogous to the InvalidSessionStrategy for the SessionManagementFilter. It also
adds a configuration option for both the InvalidSessionStrategy and
ExpiredSessionStrategy to the XML namespace and Java configuration.

Fixes: gh-3794, gh-3795

- [X] I have signed the CLA

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mdeinum Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by mdeinum** [comment]
@pivotal-issuemaster I signed that one years ago? Do I have to sign it again??

**Comment by pivotal-issuemaster** [comment]
@mdeinum Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mdeinum Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by rwinch** [comment]
Thanks for the PR! This is merged via b88418b94ae7943387edc4eaeb26c15f566845cd and 67c9f12964ba9ef87ad1c94f6562fe00d63028bd. I also applied Polish in 6650429283df5c424b6f523e25ca174433d3814d

**Pull request closed without merging**
