### PR TITLE
Fix parsing of GET SAML logout requests

### PR DESCRIPTION
**Pull request by Dyndyn**

### CODE REVIEW

**Comment by marcusdacoregio** [comment]
Hi, @Dyndyn. Thank you for the fix. Can you please target the `6.1.x` branch?

**Comment by marcusdacoregio** [comment]
Also, please run `./gradlew format check` to check if the build passes

**Comment by Dyndyn** [comment]
Hi, @marcusdacoregio. I fixed format in the test and changed target

**Comment by marcusdacoregio** [comment]
Thanks, @Dyndyn. This is now merged into `6.1.x` and `main`.

**Pull request merged**
