### PR TITLE
Update to Gradle 5.6.1

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by rwinch** [comment]
Looks like the build failed. Any ideas why it cannot find the new aspectj plugin?

**Comment by larsgrefer** [comment]
The Travis build was too fast. It tried to download it before it was finally available (the repository sometimes needs a few minutes to flush all caches)

Just restart the build and it should be fine

**Comment by larsgrefer** [comment]
I've rebased the commits to trigger a new travis build

**Comment by rwinch** [comment]
Thanks @larsgrefer This is now merged into master

**Pull request merged**
