### PR TITLE
Fixes gh-6101

### PR DESCRIPTION
**Pull request by hellosatish**
Hi @jzheaux  creating a pull request for gh-6101.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hellosatish Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6117)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=6117) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hellosatish Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=6117)!

**Comment by jzheaux** [comment]
Thanks for the PR, @hellosatish! This was merged into master via 7232dabd480d92b8dd1d401d6a51b24b72419aa5

Note that I updated the commit message to be a bit more descriptive.

**Comment by hellosatish** [comment]
@jzheaux  thanks for the updates and merge

**Pull request closed without merging**
