### PR TITLE
Allow configuration of SessionAuthenticationStrategy for CSRF

### PR DESCRIPTION
**Pull request by samiconductor**
Reasoning https://github.com/spring-projects/spring-security/issues/5300#issuecomment-501335705

Relates to #5300

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@samiconductor Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=7083)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=7083) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@samiconductor Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=7083)!

**Comment by rwinch** [comment]
Thanks for the PR @samiconductor! This was merged via 09e8ae42ed777206d043c502c6283ec6ee69db5f

**Comment by samiconductor** [comment]
Great! Thanks @rwinch. I wasn't sure what version to put for the `@since` docs. Looks like I should have put 5.2 instead of 5.1?

**Comment by rwinch** [comment]
Ahh yes good catch @samiconductor! Can you send another PR to fix?

**Pull request closed without merging**
