### PR TITLE
ci: fix GitHub Actions Deprecating save-state and set-output commands

### PR DESCRIPTION
**Pull request by kirklin**
The save-state, set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Closes gh-12032

### CODE REVIEW

**Review by marcusdacoregio — CHANGES_REQUESTED** [review]
Hi @kirklin, thanks for the PR.

We are using `echo ::set-output ...` in the `update-scheduled-release-version.yml` and `continuous-integration-workflow.yml`, can you please update those places as well?

Can you please change the target branch to `5.6.x` since it is the [oldest impacted and supported maintenance branch](https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc#create-your-branch-from-oldest-maintenance-branch).

Also, would you please change your commit message to include `Closes gh-12032` in the end? like this:

```
Your commit message

Closes gh-12032
```

**Comment by kirklin** [comment]
Handling the use of spring-io/spring-gradle-build-action@v1 still has warnings where the main branch github action test seems to work

**Comment by kirklin** [comment]
ci-test

**Comment by kirklin** [comment]
spring-gralde-warnning
The locations shown in the image indicate that there are still warnings where spring-io/spring-gradle-build-action@v1 is used

**Comment by marcusdacoregio** [comment]
I'll close this in favor of #12289

**Pull request closed without merging**
