### PR TITLE
Update AbstractRememberMeServices.java

### PR DESCRIPTION
**Pull request by SignleMR**
this file`s file encode is unkown,maybe is "Eddu Melendez"

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@SignleMR Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=4401)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=4401) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by rwinch** [comment]
Thanks the name is actually Eddú Meléndez which can be seen in the commit history at https://github.com/SignleMR/spring-security/commit/85719fcd6473ef167e58634f2e5cf1fce900b850#diff-f753d6b92cde08234575bea7652edabdR53 Would you like to update the PR?

**Comment by pivotal-issuemaster** [comment]
@SignleMR Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=4401)!

**Comment by rwinch** [comment]
Thanks @SignleMR! This is now merged into master via a1fdb7dcb3c59cf1413853f6844c6129b180bab8

**Pull request closed without merging**
