### PR TITLE
Upgrade Apache Commons Collections to v3.2.2

### PR DESCRIPTION
**Pull request by jart**
Version 3.2.1 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!

https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! This is now merged into master via 3bbcbaae9c52938fe8454ee50f908b8e06f2b49f

PS: I love to give contributors attribution in the release announcement. Do you have a preferred way for me to mention you (i.e. link to Twitter, GitHub profile, Blog, etc)

**Comment by jart** [comment]
It's very gracious of you to offer attribution. But really, all I'm doing is grepping through GitHub. If you insist, you can mention me by name and email. You're also welcome to link to my GitHub profile :)

**Comment by rwinch** [comment]
@jart I will mention your GitHub profile then. Thanks again for the contribution!

**Comment by jart** [comment]
<3

**Pull request closed without merging**
