### PR TITLE
SEC-3147: Include parameter that indicate error on authentication-failure-url as with Java Config

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've fixed SEC-3147. For details, please refer to [SEC-3147](https://jira.spring.io/browse/SEC-3147).
Please review this.
I have signed and agree to the terms of the Spring ICLA.

Thanks.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! This is now merged into master 205ef42cfbac3cb5d10c6d1e526fed403c51142e and 4.0.x 675ac80926b0968cac65e6d5d67de08d92f2620a

**Comment by kazuki43zoo** [comment]
Hi @rwinch ,

Thanks for merging and backporting :+1: 
When you plan to release the 4.0.4 ? I hope a fast release as possible !!
Thanks.

**Comment by rwinch** [comment]
@kazuki43zoo At this time there is no urgency with a 4.0.4 release. I expect it will come in Q1 of 2016.

NOTE: you can work around this issue by explicitly providing authentication-failure-url

**Comment by kazuki43zoo** [comment]
@rwinch  thinks for quick answer !

> At this time there is no urgency with a 4.0.4 release. I expect it will come in Q1 of 2016.

Yes. i agree your opinion !! 
I  wanted to know a release plan because write a guideline(best practice) how to use spring security 4.0+. (In guideline, i plan to support both  Java Config and XML Config)

Incidentally ..., when you plan to release the 4.1 ?

> you can work around this issue by explicitly providing authentication-failure-url

Yes ! Currently, i applied a workaround using `authentication-failure-url`.

Thanks.

**Comment by rwinch** [comment]
@kazuki43zoo A GA of 4.1 is expected in Q1 of 2016.

**Comment by kazuki43zoo** [comment]
@rwinch Thanks for answer. i will wait a 4.1 GA.

**Pull request closed without merging**
