### PR TITLE
#9511: Fix for OidcClientInitiatedLogoutSuccessHandler. Now encodes a…

### PR DESCRIPTION
**Pull request by hosea**
…lready encoded queryparameters in postLogoutRedirectUrl correctly

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hosea Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9672)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=9672) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hosea Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=9672)!

**Comment by jzheaux** [comment]
Thanks, @hosea for the PR!

It looks like the build is failing due to some missed formatting requirements. These can be fixed by running `./gradlew format`.

Also, for your squashed commit, will you please format it like so:

```
Fix post_logout_redirect_uri Encoding

Closes gh-9511
```

This way GitHub will close the issue automatically and it will be a bit easier to find additional details about the fix in the future.

**Comment by jzheaux** [comment]
Hi, @hosea, are you able to make the requested changes?

**Comment by jzheaux** [comment]
Thanks, @hosea, for your contribution! I've merged it into `main` via b671a960738647ed176d56b70397a722a9b2b1e0 and a polish of 65ecaa0c283bc3d7aed19faf9927ec6306e6e4cb.

**Pull request closed without merging**
