### PR TITLE
The SecuredAuthorizationManager can now find @Secured annotations on …

### PR DESCRIPTION
**Pull request by abimael-turing**
…subclasses when a method in the superclass is called.

closes the issue #15002

### CODE REVIEW

**Comment by abimael-turing** [comment]
@artem103 and @spring-projects-issues, I completed the pull request, but the build is failing on GitHub due to deprecated Gradle features, which are incompatible with Gradle 8.0.

**Comment by abimael-turing** [comment]
@artem103 and @spring-projects-issues, I completed the pull request, but the build is failing on GitHub due to deprecated Gradle features, which are incompatible with Gradle 8.0.

image

**Comment by rishiraj88** [comment]
> @artem103 and @spring-projects-issues, I completed the pull request, but the build is failing on GitHub due to deprecated Gradle features, which are incompatible with Gradle 8.0.
> 
> image

@abimael-turing , how did you start this build- with 'gradlew' or 'gradle' executable directly? gradlew is well known to handle cross-version compatibility issues.

**Comment by jzheaux** [comment]
@abimael-turing, I'm not yet certain if we will be able to backport this to a maintenance version, however I've updated the branch so that it builds.

To more fully backport this behavior, will you please consider changing the PR to cherry-pick b0da37d4fa8a1365dccdc71501e147b40502aa15 instead? In this way, all the annotations will get the same benefit.

In the meantime, I'd like to see how the feature is received in 6.3 before merging.

**Comment by jzheaux** [comment]
After some additional research, @abimael-turing, this feature was reverted in https://github.com/spring-projects/spring-security/commit/f20ae1a71c81df00e10de48ffab79fa4b6c35c02 for `6.3.x` and onward. 

As such, I'm going to close this issue. In general, annotations declared lower in the hierarchy do not affect methods higher in the hierarchy.

**Pull request closed without merging**
