### PR TITLE
fix AuthenticationFailureBadCredentialsEvent published twice

### PR DESCRIPTION
**Pull request by clevertension**
#6281 
this pr fix the issue of AuthenticationFailureBadCredentialsEvent published twice

### CODE REVIEW

**Comment by jgrandja** [comment]
@clevertension Thanks for the PR. However, I already have a [fix](https://github.com/jgrandja/spring-security/commit/22af1b742c88cdef7e8020ddf007702ad9d6ae7b) for this and pushed it to my fork.

I'm holding off on merging this until I get a response from you from my [comment](https://github.com/spring-projects/spring-security/issues/6281#issuecomment-448711363).

As an FYI, it's best to see if an issue is assigned before you start work on it so you don't waste any of your time. This issue was already assigned to me. I would have been more than happy to have you work on it if you initially requested it. However, we still need to have the discussion first to ensure we are on the same page. Can you please respond to my comment so I can better understand your scenario. Thanks.

**Comment by clevertension** [comment]
@jgrandja , 
1. thanks for your remind, i will apply for the issue before i plan to work on it at next time
2. after i review and test your code carefully, i think you may fail to pass the **authenticationExceptionFromParentOverridesPreviousOnes** test case in **ProviderManagerTests**, so i think it is not so easy to fix this issue

3. yes,discussion is very important, i will give a demo project ASAP,

**Comment by jgrandja** [comment]
@clevertension I reviewed your PR and your changes **do not** allow for duplicate failure events to be published. Although this is the behaviour we want in order to resolve #6281, this is not what triggered your initial [comment](https://github.com/spring-projects/spring-security/issues/6281#issuecomment-448154352):

> so i think it is reasonable to publish twice AuthenticationFailureBadCredentialsEvent here, because they are authenticated from two AuthenticationManager, it is just a coincidence that the two AuthenticationManager throw the same Failure Exception

So I guess I'm confused at this point as you originally argued that the `AuthenticationFailureBadCredentialsEvent` resulting from `BadCredentialsException` in the child and parent `AuthenticationManager` should both get published. However, the changes in your PR does not allow for duplicated events to be published.

As already mentioned in this [comment](https://github.com/spring-projects/spring-security/pull/6313#issuecomment-449032331), I have a fix for #6281 so I'm going to close this PR.

It is still not clear to me if you are facing a specific issue? If you are, please provide a sample that reproduces the issue so I can better understand your use case. Also, please log a new ticket providing the details and link to this issue. Thanks.

**Comment by clevertension** [comment]
yes, i meet with this issue #6324 , we can talk to there

**Pull request closed without merging**
