### PR TITLE
Apply defaults

### PR DESCRIPTION
**Pull request by ab0159w**
Not all defaults are overridden in provided sample, which did not work

### CODE REVIEW

**Comment by ab0159w** [comment]
> Thanks for reaching out @ab0159w. Could you share some more information about your use-case and why the given configuration did not work for you? Given my understanding, it is working as I would expect.

Angular application calling spring cloud gateway secured with spring security (reactive) and keycloak. Will investigate further later in the week to see if I can see the exact cause.

**Comment by eleftherias** [comment]
Thanks @ab0159w, a sample that reproduces the problem would be especially helpful.

**Comment by eleftherias** [comment]
@ab0159w Have you had the chance to investigate this further?

**Comment by ab0159w** [comment]
@eleftherias Sorry, have not investigated further yet.

**Comment by ab0159w** [comment]
@eleftherias removed the .applyPermitDefaultValues() and it is working for me, must have been allowed-origins or allowed-headers that was causing the issue initially. Closing PR.

**Pull request closed without merging**
