### PR TITLE
Cache request URI in cookie instead of session

### PR DESCRIPTION
**Pull request by eleftherias**
Fixes: gh-7157

### CODE REVIEW

**Comment by jzheaux** [comment]
@eleftherias thanks for this PR - it doesn't sound much like the description in #7157. Would you mind adding some of your thinking that led you to this conclusion? Maybe add it as a comment in the original ticket.

**Comment by rwinch** [comment]
@jzheaux There was some offline discussion about this between @eleftherias. Since she is on PTO I went ahead and added a comment to the original issue

**Comment by jzheaux** [comment]
One thing to think about here is that there might be end-users who are affected by this change during an upgrade.

For example, let's say that an end-user was in the middle of logging in when the the upgrade happened. Their remembered URI could be in the session, but when Spring Security tries to do the redirect after login, it will now look for it in a cookie (and fail to find it).

I believe the impact is probably minor, but let's weigh it before merging. Also, we should add a release note about it.

If it appears the impact will be large, it might be possible to introduce a strategy that consults multiple request caches, if we wanted to try and be passive.

**Comment by rwinch** [comment]
I think perhaps we should split this into two items. One introducing the cookie cache and then separately consider making it it a default.

**Comment by eleftherias** [comment]
I create gh-8033 for the server cookie cache.

**Comment by rwinch** [comment]
Closing this in favor of  gh-8033 for support of storing in a cookie. I don't think we should make storing in a Cookie as a default as it isn't as secure as using the session. Instead, I think we should proceed by making the request unique (i.e. add a query parameter) so it is only looked up on log in success.

**Pull request closed without merging**
