### PR TITLE
Document OAuth2 Client behind proxy and redirect_uri

### PR DESCRIPTION
**Pull request by bedla**
Hi,
pls see https://github.com/spring-projects/spring-security/issues/7312 for details.
I am not sure if hyperlinked URL to Spring Boot docs is correct (version?). And if I should add that TIP to samples.
Thx
Ivos

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! Please link to our documentation about using a proxy server https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#appendix-proxy-server

**Comment by bedla** [comment]
I have updated PR. But still I am no sure about that link to Spring Boot documentation. Should I remove that link to SNAPSHOT?

**Comment by luvarqpp** [comment]
Just a sidenote, there could be probably also some place, where to add advice like this one (checking filter order):
https://github.com/spring-projects/spring-framework/issues/23647#issuecomment-535423337

PS: Thanks for improving documentation.

**Comment by jgrandja** [comment]
Thanks for the PR @bedla. This is now in master!
FYI, I added a little polish to the docs.

**Comment by bedla** [comment]
cool, thx for merge :]

**Pull request closed without merging**
