### PR TITLE
Fixed Interceptor name in Method Security reference document

### PR DESCRIPTION
**Pull request by irerin07**
Changed the interceptor name from `AuthenticationManagerBeforeMethodInterceptor `to `AuthorizationManagerBeforeMethodInterceptor` in the section [Each Annotation Has Its Own Method Interceptor](https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html#annotation-method-interceptors)

I tried to find the `AuthenticationManagerBeforeMethodInterceptor `in the project but couldn't find it. 

Also the link provided in the reference doc was actually a link to `AuthorizationManagerBeforeMethodInterceptor`.

### CODE REVIEW

**Comment by jzheaux** [comment]
Hi, @irerin07. It looks like the PR build failed due to some formatting constraints. WIll you please rebase to the latest and push again?

**Comment by irerin07** [comment]
Hi, @jzheaux . I don't know if I did what you asked correctly but can you check whether this is the right way to do so?
Thank you.

**Comment by jzheaux** [comment]
Thanks for the attempt, @irerin07! I went ahead and took care of the rebase this time.

**Comment by irerin07** [comment]
@jzheaux Thank you very much and sorry for any inconveniences.

**Pull request merged**
