### PR TITLE
Update User.java

### PR DESCRIPTION
**Pull request by AlterEgoDev**
fixed a typo; replaced "User.witUsername("user")" with "User.withUsername("user")"

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@AlterEgoDev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=5150)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=5150) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by rwinch** [comment]
Thanks for the PR! This is an obvious fix so there is no need to sign the CLA

**Comment by pivotal-issuemaster** [comment]
@AlterEgoDev This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by rwinch** [comment]
Thanks again for the PR @AlterEgoDev! This is merged into master

**Comment by pivotal-issuemaster** [comment]
@AlterEgoDev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=5150)!

**Pull request merged**
