### PR TITLE
Task name changed from publishMavenJavaPublicationToLocalRepository to publishMavenJavaPublicationToBuildDirectoryRepository

### LINKED ISSUE #11475: Change task publishMavenJavaPublicationToLocalRepository to publishMavenJavaPublicationToBuildDirectoryRepository
Local could be interpreted as `~/.m2/repository` or perhaps other locations.

Changing the name clarifies that it is going to the repository in the project's build directory.

### PR DESCRIPTION
**Pull request by priya1712d**
Closes #11475

### CODE REVIEW

**Comment by jzheaux** [comment]
Hi, @priya1712d. We also need to edit the task itself in `buildSrc`. If done correctly, you should be able to run `./gradlew publishMavenJavaPublicationToBuildDirectoryRepository` on your local machine and see the Spring Security jars copied to `{PROJECT_DIR}/build/publications/repos`.

It appears that `PublishLocalPlugin` may be where the change needs to be made.

**Comment by priya1712d** [comment]
@jzheaux  
Thanks !!! 
I will work on this today.

**Comment by jzheaux** [comment]
Hi, @priya1712d! Are you able to address the requested changes? If you are busy, I can provide a polish commit to complete the PR.

**Comment by jzheaux** [comment]
I'm closing this PR due to lack of progress. We can restart a new one if needed.

**Pull request closed without merging**
