### PR TITLE
Data flow style change from if-else to water flow.

### PR DESCRIPTION
**Pull request by mosbat**
Hi guys, I'd like to contribute even with small changes or improvements for practice or just to purely satisfy my coding habits.

I found an if else statement and after studying/observing it for a while, it felt a bit awkward (understandably); and would love to propose just a mere style change from if-else to waterfall style.

I do not expect you to like my changes; but if you'd like to discuss them or you have the same passion as I do, I'm happy to listen to comments and maybe hints.

I was thinking btw, the class is deprecated but still seems to be in use, or am I wrong?

### CODE REVIEW

**Comment by mosbat** [comment]
fixes #16119

**Comment by sjohnr** [comment]
@mosbat Thank you for wanting to contribute!

> I'd like to contribute even with small changes or improvements for practice or just to purely satisfy my coding habits.

Changing code style to suit preference is something best done in your own projects or fork of Spring Security. I don't find precedent for accepting PRs that change code style simply due to preference. Please identify an actual issue with the code, and please consider opening an issue first to discuss it as outlined in the [contributing guidelines](https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc#find-an-issue) (unless it is a trivial change that contains an obvious fix, such as a typo in documentation).

> I do not expect you to like my changes; but if you'd like to discuss them or you have the same passion as I do, I'm happy to listen to comments and maybe hints.

This issue tracker is not a discussion forum, so I don't feel it would be productive to have these discussions here unless it is directly relevant to an issue.

For the above reasons, I am going to close this PR. Please consider looking at the `ideal-for-contribution` label as an alternative to try your hand at small issues/PRs.

**Comment by sjohnr** [comment]
Apologies I missed the issue you opened first. However, I will also close the issue as a duplicate.

**Comment by mosbat** [comment]
> @mosbat Thank you for wanting to contribute!
> 
> > I'd like to contribute even with small changes or improvements for practice or just to purely satisfy my coding habits.
> 
> Changing code style to suit preference is something best done in your own projects or fork of Spring Security. I don't find precedent for accepting PRs that change code style simply due to preference. Please identify an actual issue with the code, and please consider opening an issue first to discuss it as outlined in the [contributing guidelines](https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc#find-an-issue) (unless it is a trivial change that contains an obvious fix, such as a typo in documentation).
> 

Actually, if-else is considered as a bad practice as they produce bugs on the long-run, but nevermind; and I did open an issue; but probably it's my failure since you couldn't see the issue referenced here.

> > I do not expect you to like my changes; but if you'd like to discuss them or you have the same passion as I do, I'm happy to listen to comments and maybe hints.
> 
> This issue tracker is not a discussion forum, so I don't feel it would be productive to have these discussions here unless it is directly relevant to an issue.
> 

I'm confused because in a previous issue, I asked about changes and contributions that are welcomed, and you said that I can go ahead and try as long as they are focused and specific. The issue linked to this PR, I labeled it as enhancement.

My conclusion, you are more interested in fixing bugs or critical performance issue, correct me if am wrong ...

> For the above reasons, I am going to close this PR. Please consider looking at the `ideal-for-contribution` label as an alternative to try your hand at small issues/PRs.

I don't mean to be rude, I'm just asking for clarification.

**Pull request closed without merging**
