### PR TITLE
Polish OAuth2ClientConfiguration

### PR DESCRIPTION
**Pull request by kse-music**
Use constructor inject and use `ObjectProvider.getIfUnique` instead of list.size == 1

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks for the cleanup, @kse-music! Will you please add some more detail to your Git commit so that it is clear from reading the title what is going on? In the absence of a ticket that already has this detail, it would also be helpful if the commit had a description as to the benefit of this commit.

Second, I imagine that this pattern of taking a list and checking the size is common in Spring Security. Can you update the PR to clean up other places as well (e.g. `OAuth2ClientConfiguration`, `AbstractSecurityWebSocketMessageBrokerConfigurer`, etc.).

Finally, I think it would be better to do the `Arrays.asList` -> `Collections.singleton` maneuver in a separate PR since there are likely many places where this appears as well.

I can help with additional commits for anything you feel you don't have time for.

**Comment by kse-music** [comment]
@jzheaux After inspection, only `OAuth2ClientConfiguration`, `OAuth2ClientWebFluxSecurityConfiguration`, and `AbstractSecurityWebSocketMessageBrokerConfigurer `were found to have the only bean judgment in the `spring-config module`. All except `AbstractSecurityWebSocketMessageBrokerConfigurer `have been modified because it tag deprecated.
 
If I have overlooked anything or other needs to be revised, please feel free to add it.

**Comment by rwinch** [comment]
> Finally, I think it would be better to do the Arrays.asList -> Collections.singleton maneuver in a separate PR since there are likely many places where this appears as well.

Note that `Arrays.asList` is mutable and `Collections.singleton` is not. Switching to an immutable `Collection` would be considered as a breaking change.

**Comment by jzheaux** [comment]
@rwinch, I learned something new today. :) I had always thought `Arrays.asList` was immutable since I couldn't add or remove from it. However, you can use `set(index, value)`. Good catch.

**Pull request merged**
