### PR TITLE
Docs ->  Servlet Applications Authentication  -> Form Login & Persistence 

### PR DESCRIPTION
**Pull request by nimakarimiank**
### FormLogin docs change
**`UsernamePasswordAuthenticationFilter` Definition raises confusion**

as written in the docs : "When the username and password are submitted, the `UsernamePasswordAuthenticationFilter` authenticates the username and password.", It states that `UsernamePasswordAuthenticationFilter ` is responsible for Authenticating users and populating the `SecurityContext`. instead as stated later we read : "`UsernamePasswordAuthenticationFilter` creates a `UsernamePasswordAuthenticationToken`, which is a type of [Authentication](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-authentication), by extracting the username and password from the HttpServletRequest instance."
I think we should change the docs so it wouldn't raise any confusions. 

### Wrong Class reference 
**`SecurityContextPersistenceRepository`** is not a recognized class, it's a typo for `SecurityContextRepository`

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks, @nimakarimiank! Will you please update the PR so each commit atomically describes what is being changed? For example instead of `docs modification`, you could do:

```
Fix SecurityContextPersistenceRepository Typo
```

and 

```
Clarify `UsernamePasswordAuthenticationFilter` Workflow
```

etc.

Please also squash the two commits that are for the same line in the documentation.

**Comment by nimakarimiank** [comment]
hey @jzheaux, 
please take a look and let me know if it's ok.
Thanks!

**Comment by jzheaux** [comment]
Thanks for the updates, @nimakarimiank. Will you please take a look at the commits again? Now there are 7, and we want to have 3. It may help for you to rebase with main.

**Comment by nimakarimiank** [comment]
@jzheaux This should fix the commit clarity issue 
we have 2 commits, 1 for each change that I proposed to the docs.
1- Clarify UsernamePasswordAuthenticationFilter Workflow

> for Form.adoc 

2- Fix SecurityContextPersistenceRepository Typo

> for Persistence.adoc

Does it look good to you ?

**Comment by jzheaux** [comment]
Thanks, @nimakarimiank! I went ahead and made the final adjustment to rebase with Spring Security's `main` branch.

In the future, I recommend creating a branch and pushing from there instead:

```
git checkout -b my-fixes
// add the commits you want
git push origin my-fixes
```

Then your PR is from `my-fixes` to `main`. This will help your `main` stay in line with Spring Security's `main` and also make it simpler to rebase a PR when that's needed.

This is now merged into `main`, nice job!

**Pull request merged**
