### PR TITLE
Use the 'io.freefair.aspectj' gradle plugin

### PR DESCRIPTION
**Pull request by larsgrefer**
After I've migrated (or removed) the other gradle plugins in #7077 #7173 and #7174 the AspectJ plugin was the last remaining one. Instead of migrating the current groovy based plugin to java, I just used the AspectJ gradle plugin I've already written last year.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR @larsgrefer! We'd love to rely on proper AspectJ Gradle plugin. However, it appears this PR broke the build. Can you take a look at that?

**Comment by larsgrefer** [comment]
@rwinch The build is fixed now.

**Comment by rwinch** [comment]
Is there a reason that we need to move the source code into a different source folder? I'd prefer to keep the code in the src/main/java folder.

**Comment by larsgrefer** [comment]
The `io.freefair.aspectj` plugin uses `src/main/aspectj` as source root for the code to be compiled by `ajc` by default. (The same way like `src/main/groovy` would contain code for `groovyc` and `src/main/kotlin` would contain the code compiled by `kotlinc`).

If you like, this can be changed in the build script:
```gradle
sourceSets.main.aspectj.srcDir "src/main/java"
```

Another option would be the `io.freefair.aspectj.post-compile-weaving` plugin.
This plugin leaves the actual compilation to javac (or groovyc, kotlinc, ...) and only performs the weaving as bytecode-to-bytecode transformation (by passing the compiler output into ajc's `--inpath`)

**Comment by rwinch** [comment]
I think I'd like to use `sourceSets.main.aspectj.srcDir "src/main/java"`. My reasoning is that while it makes sense from a Gradle plugin perspective that aspectj code is place in it's own source folder it feels a bit invasive.

Spring allows switching between proxy and compile time aspects with just configuration. It is a bit disruptive to switch the folder that the annotated Java code is in.

**Comment by larsgrefer** [comment]
> I think I'd like to use sourceSets.main.aspectj.srcDir "src/main/java". My reasoning is that while it makes sense from a Gradle plugin perspective that aspectj code is place in it's own source folder it feels a bit invasive.

For the `aspects` project this is actually the only option because its aspect is an `*.aj` file, which has to be compiled by `ajc`.

For `samples/javaconfig/aspectj` and `samples/xml/aspectj` I've chosen the `post-compile-weaving` approach because it's even less invasive and provides better integration:
 - The `post-compile-weaving` plugin can also weave groovy, scala and kotlin classes
 - Since the acutal compilation is perfomed by `javac`, additional tooling like lombok could be used without problems.

**Comment by rwinch** [comment]
Thanks for the PR @larsgrefer! This is now merged into master

**Pull request merged**
