### PR TITLE
SessionRegistryImpl uses Map.compute

### PR DESCRIPTION
**Pull request by jeffrey-easyesi**
Adding/removing sessions from principals wasn't atomic. If one thread removed the last session from a principal while another thread added a new one, the addition could be lost. (gh-3189)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jeffrey-easyesi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=7178)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=7178) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by jeffrey-easyesi** [comment]
This is a much smaller change than it looks due to indentation changes. https://github.com/spring-projects/spring-security/pull/7178/files?w=1

**Comment by pivotal-issuemaster** [comment]
@jeffrey-easyesi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=7178)!

**Comment by rwinch** [comment]
Thanks for the PR @jeffrey-easyesi This is now merged into master via a17d66463db3528834c201deef60cccb70a23161

**Pull request closed without merging**
