### PR TITLE
Update JwtTimestampValidator.java

### PR DESCRIPTION
**Pull request by ajavorskidev**
Changed maxClockSkew to clockSkew in the file JwtTimestampValidator.java

Just simplified the MaxClockSkew to clockSkew regarding the issue 
Fixes: gh-6380

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks for the PR, @ajavorskidev! 

Will you please adjust the commit message so that it contains the ticket that is fixed? You can see an example in [the contribution guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#format-commit-messages)

**Comment by ajavorskidev** [comment]
Have just created a new commit and added the ticket it fixes!

**Comment by jzheaux** [comment]
Nice, @ajavorskidev, thank you. Last step, will you please [squash your commits](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#squash-commits)?

**Comment by ajavorskidev** [comment]
I'm having a bit of trouble squashing the commits together! After I save the rebase, how do I push the edit?

**Comment by ajavorskidev** [comment]
Im just going to close this pull request and try again!

**Pull request closed without merging**
