### PR TITLE
chore: Use cache in continuous-integration-workflow.yml

### PR DESCRIPTION
**Pull request by jongwooo**
Signed-off-by: jongwooo <jongwooo.han@gmail.com>

## Description

Updated `continuous-integration-workflow.yml` to cache dependencies using [actions/setup-java](https://github.com/actions/setup-java#caching-packages-dependencies). `setup-java@v3` or newer has caching **built-in**.

### About caching workflow dependencies
Jobs on GitHub-hosted runners start in a clean virtual environment and **must download dependencies each time**, causing increased network utilization, longer runtime, and increased cost. To help speed up the time it takes to recreate files like dependencies, GitHub can cache files that frequently use in workflows.

### Solutions
Java projects can run faster on GitHub Actions by enabling dependency caching on the [setup-java](https://github.com/actions/setup-java) action. `setup-java` supports caching for both Gradle and Maven projects.

**AS-IS**

```yaml
- name: Set up JDK 17
  uses: actions/setup-java@v3
  with:
    java-version: '17'
    distribution: 'temurin'
```

**TO-BE**

```yaml
- name: Set up JDK 17
  uses: actions/setup-java@v3
  with:
    java-version: '17'
    distribution: 'temurin'
    cache: 'gradle'
```

> It’s literally a one line change to pass the `cache: 'gradle'` input parameter.

## References
[actions/setup-java#caching-packages-dependencies](https://github.com/actions/setup-java#caching-packages-dependencies)
[How to build Gradle projects with GitHub Actions](https://tomgregory.com/build-gradle-projects-with-github-actions/#5_Enable_Gradle_caching)

### CODE REVIEW

**Comment by jzheaux** [comment]
Thanks, @jongwooo. Will you please rebase this to `5.7.x` so that we can apply this to all branches?

**Comment by jongwooo** [comment]
@jzheaux I tried to rebase with `git rebase 5.7.x`, but it resulted in a conflict. It would be grateful if you could tell me how to rebase it.

**Comment by jzheaux** [comment]
Try this, please:

```bash
git checkout 5.7.x
git cherry-pick 7a9eb93b34e0233dd3a3dbc39f2f858639a6c5a9
git push ${remote} +chore/use-setup-java-action-to-cache-dependencies
```

where `${remote}` is the remote for your fork. It may be `origin`, for example.

Then, change the base of this PR to `spring-projects:5.7.x`.

**Comment by jongwooo** [comment]
@jzheaux I made a mistake and the PR was closed. So I reopened at #12503

**Pull request closed without merging**
