### PR TITLE
Add validation when rememberMeServices and rememberMeCookieName are

### PR DESCRIPTION
**Pull request by eddumelendez**
- [X] I have signed the CLA

provided

Fixes gh-3909

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@eddumelendez Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by eddumelendez** [comment]
@rwinch signed!

**Comment by pivotal-issuemaster** [comment]
@eddumelendez Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

**Comment by pivotal-issuemaster** [comment]
@eddumelendez Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by eddumelendez** [comment]
@rwinch any comment about this? Thanks!

**Comment by rwinch** [comment]
Thanks for the PR! This is now merged into master via 87224f62e4e0c2e13f3087d4b2441bd90ecf3449 I have also added a little bit of polish via 26ad1cb4a5c8a8b1f8554566a08b5900bd85b235

**Pull request closed without merging**
