### PR TITLE
First attempt at fixing https://jira.spring.io/browse/SEC-3066

### PR DESCRIPTION
**Pull request by Stexxen**
I have added a new method to AclService. Not ideal, buts its just to start the ball rolling.

### CODE REVIEW

**Comment by Stexxen** [comment]
Realised the branch name is still master. apologies for that.

**Comment by rwinch** [comment]
Thanks for the PR. Unfortunately we cannot add a new method to an interface since this would be a non passive change.

**Comment by Stexxen** [comment]
Yep, completely understand, so have come up with a much better solution here
https://github.com/spring-projects/spring-security/pull/215

**Comment by Stexxen** [comment]
@rwinch is the new PR acceptable?

**Comment by rwinch** [comment]
@Stexxen - Can you include a test? If the PR is accepted, the test will ensure the issue doesn't happen again. Furthermore, a test will help me to better understand when the issue occurs.

I'm quite hesitant to perform a try catch with only a logger in it without knowing all the details.

**Comment by pivotal-issuemaster** [comment]
@Stexxen Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by pivotal-issuemaster** [comment]
@Stexxen Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by rwinch** [comment]
Closing as we do not want to add a new method on an interface

**Pull request closed without merging**
