### PR TITLE
Fix: Typo in DelegatingPasswordEncoder's Javadoc

### PR DESCRIPTION
**Pull request by theHacker**
Obvious Fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@theHacker Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=4983)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-security&pullRequestId=4983) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@theHacker This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by rwinch** [comment]
Thanks for the PR! This is merged into master.

PS If you have a typo or other obvious fix, you can make the issuemaster happy by adding `Obvious Fix` to your description (that is why I changed it)

**Comment by theHacker** [comment]
Thx for the tip, this is good to know :smile:

**Pull request merged**
