### PR TITLE
Fix gh-10214

### PR DESCRIPTION
**Pull request by djechelon**
References #10214

### CODE REVIEW

**Comment by djechelon** [comment]
Checkstyle doesn't like IDEA's reformat

**Comment by jzheaux** [comment]
Thanks, @djechelon! To simplify future maintenance, will you please squash your commits?

**Comment by djechelon** [comment]
Yea. Amend simply pretended to work.

So now you deserve a mandatory friday fun
meme

**Comment by jzheaux** [comment]
Thanks, @djechelon! I adjusted the commit message to work better with our automation, and now it's merged via  4302a86fad195731f986953d92556a2c755cd8f7.

**Pull request closed without merging**
