### PR TITLE
Allow negative values to configure unlimited sessions

### LINKED ISSUE #3899: It's not possible to configure unlimited number of sessions when using xml config / concurrency-control
### Summary

I want to use concurrency-control inside xml configuration, mainly to use session registry, without limiting number of sessions. 

`ConcurrentSessionControlAuthenticationStrategy` states in #setMaximumSessions "The default value is 1. Use -1 for unlimited sessions.". 

### Actual Behavior

Cannot configure max-sessions="-1" because value is a positive integer in XSD, parsing fails.

### Expected Behavior

```<concurrency-control max-sessions="-1" />```

Is a valid configuration.

### Version

4.1.0.RELEASE and lower.

### PR DESCRIPTION
**Pull request by michael-simons**
Fixes #3899

- [x] I have signed the CLA

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@michael-simons Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by michael-simons** [comment]
Done.

**Comment by pivotal-issuemaster** [comment]
@michael-simons Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](null) to manually synchronize the status of this Pull Request.

See the [FAQ](null) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rwinch Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-security&pullRequestId=3900)!

**Comment by pivotal-issuemaster** [comment]
@michael-simons Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

**Comment by rwinch** [comment]
Thanks this is now merged into master via e3ff4130a5dd6784d946e10dffa2785b5e46461d with some polish e297706e8bfda38117a99fd06dace74c5a8cc5f1

NOTE: We modify the .rnc file which generates the xsd file

**Pull request closed without merging**
