### PR TITLE
Add WebFlux support for spring security web jackson module.

### LINKED ISSUE #6303: Add WebFlux support for spring security web jackson module
Create new jackson module for spring-web-flux.

### PR DESCRIPTION
**Pull request by finke-ba**
Linked with #6293

Fixes #6303

### CODE REVIEW

**Comment by finke-ba** [comment]
@rwinch What you mean?

**Comment by finke-ba** [comment]
@rwinch hello, I hope I did it right. Could you please check it?

**Comment by finke-ba** [comment]
@rwinch sure, I'll add. But I also didn't do it for #6304 which is already merged into master..

**Comment by finke-ba** [comment]
@rwinch, done!

**Comment by rwinch** [comment]
> But I also didn't do it for #6304 which is already merged into master..

Thanks for the heads up. I noticed this but it is too late. It isn't the end of the world though.

> done!

Thanks for yet another contribution! You are on fire! This is now merged into master.

**Pull request merged**
