### PR TITLE
Validate @EnableGlobalMethodSecurity usage

### PR DESCRIPTION
**Pull request by ayudovin**
adding warn that in the composition of all global method configuration, no annotation support was actually activated.
this [improvement](https://github.com/spring-projects/spring-security/issues/5341)

### CODE REVIEW

**Comment by jzheaux** [comment]
@ayudovin Thanks for the PR! 

Instead of logging a warning, let's throw an `IllegalStateException`. While it is nice that a warning makes this a passive update for folks, misconfiguration like this is a security vulnerability, and we want to make sure that users fix it.

Also, in that case, it should be possible to create a test around it. Would you mind adding one?

**Comment by ayudovin** [comment]
@jzheaux , I have added changes by suggestion.

**Comment by jzheaux** [comment]
Thanks @ayudovin for the PR! This has been merged to master with 1e864ad7645fcf6d66edd714cb4faf32f76c0716.

Also, I did just a bit of polish with 73c1abbba03e1a9e799a25bb7a6528a19eb6dd36.

**Comment by ayudovin** [comment]
@jzheaux, thank you!

**Pull request closed without merging**
