### PR TITLE
ActiveDirectoryLdapAuthenticationProvider uses InternalAuthenticationServiceException

### PR DESCRIPTION
**Pull request by dadikovi**
…ication exceptions in InternalAuthenticationServiceException 
GitHub issue: gh-2884

**This is just a proposal without new test cases or documentations.**

Please let me know what kind of test/documentation changes should I make together with this change.

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the PR! Can you please add a test and update the commit message to match our conventions listed in [CONTRIBUTING](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.adoc#format-commit-messages)? Something like:

```
ActiveDirectoryLdapAuthenticationProvider Wraps CommunicationException

CommunicationException are now wrapped in InternalAuthenticationServiceException

Closes gh-2884
```

**Comment by dadikovi** [comment]
I sent another iteration of this PR, but I have a few question:

- CommunicationException is thrown from bindAsUser and searchForUser methods as well, so I changed the doAuthentication method (bindAsUser is now in the try-block as well), because I wanted to keep this wrapping logic in one place. (Please review my decision :) )
- I had to introduce a new error message, I put it in messages.properties. Since I'm new here I don't know if I should take care of the translations or not?
- I can imagine that someone expects that a CommunicationException is thrown if LDAP is not accessible, so this change is an API-breaking change for them. Should I write some changelog or documentation about it?

**Comment by dadikovi** [comment]
(Also, I will fix the issues as soon as I can)

**Comment by rwinch** [comment]
Thanks for the Pull Request! This is now merged into master via f7b33da5775d2bef504c1671a83a52e48759d13b :smile:

**Pull request closed without merging**
